### ISSUE TITLE
The `value` in the `var` is required

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#1006]
### Description

The `value` in the `var` is required

### Problem Statement/Justification

There are times when you may want to set `value` to undefined.

### Proposed Solution or API

`ui-props.ts`
```diff ts
  var: {
    isProcessSkip: true,
    transform: "var",
-    type: '{ __prefix?: string; name: string; token?: keyof Omit<Theme, "components" | "colorSchemes" | "themeSchemes">, value: Token<StringLiteral | number> }[]',
+    type: '{ __prefix?: string; name: string; token?: keyof Omit<Theme, "components" | "colorSchemes" | "themeSchemes">, value?: Token<StringLiteral | number> }[]',
    hasToken: false,
    description: [
```

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by atsushi729** [comment]
Hi, can I contribute this issue??

**Comment by 108yen** [comment]
@atsushi729 
Thank you!
I assigned you. Good luck!

**Comment by atsushi729** [comment]
@108yen
Thank you for assigning this to me. 

Quick question: could the issue be resolved by making the value an optional property, as you suggested? 
FYI : I've already tried this, ran `pnpm test`, and all tests passed. 
```
  var: {
    isProcessSkip: true,
    transform: "var",
-    type: '{ __prefix?: string; name: string; token?: keyof Omit<Theme, "components" | "colorSchemes" | "themeSchemes">, value: Token<StringLiteral | number> }[]',
+    type: '{ __prefix?: string; name: string; token?: keyof Omit<Theme, "components" | "colorSchemes" | "themeSchemes">, value?: Token<StringLiteral | number> }[]',
    hasToken: false,
    description: [
```

**Comment by 108yen** [comment]
@atsushi729 
Yes, this modification is sufficient.

**Comment by atsushi729** [comment]
@108yen 
I'm sorry to ask again, but could I check the rules for pull requests?

 Since the files I modified this time are outside of the components and can't be selected from the changeset list, should I generate an empty file and write it as follows?

```
---
"@yamada-ui/generate-css": patch
---

Redefined value as optional property.
```

**Comment by 108yen** [comment]
@atsushi729 
①Run `pnpm gen:css`.
②Files are automatically generated based on the modified `ui-props.ts`.
③Run `pnpm changeset` and chose `yamada-ui/core`
