### ISSUE TITLE
`pnpm gen:token` is not working

### ISSUE THREAD

**Issue by suzukisan22** [yamada-ui/yamada-ui#1018]
### どのパッケージに問題がありますか？

@yamada-ui/react

### パッケージのバージョン

1.2.11

### 概要

when I try command `pnpm gen:token`, command not found. 
in package.json, I found command `gen:tokens`. document should be fixed. (or script should be) 

#### contribution
https://github.com/hirotomoyamada/yamada-ui/blob/ade975c5c6f228af59fca785dd1945709ad6e033/CONTRIBUTING.ja.md#L49
https://github.com/hirotomoyamada/yamada-ui/blob/ade975c5c6f228af59fca785dd1945709ad6e033/CONTRIBUTING.md#L51

### package.json
https://github.com/hirotomoyamada/yamada-ui/blob/ade975c5c6f228af59fca785dd1945709ad6e033/package.json#L36

### 再現手順

in terminal, do execute `pnpm gen:token`, it happens.

### ブラウザ

None

### OS

- [X] macOS
- [ ] Windows
- [ ] Linux

### まさか、問題の修正方法をご存知ですか？

はい

### この問題の修正に参加し、修正を含むプルリクエストを作成しますか？

None

### 追加情報

document fixed (or command fixed)

**Comment by hirotomoyamada** [comment]
Hi, thanks for the PR.

What you should change is `CONTRIBUTING.md`. Please change to `pnpm gen:tokens`.
