### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/color-picker`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1026]
package: @yamada-ui/color-picker

### Description
`@yamada-ui/color-picker` has a test coverage of less than 80%. We will enhance it to above 80%.

### Target files
- [packages/components/color-picker/src/alpha-slider.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/alpha-slider.tsx)
  - [L13](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/alpha-slider.tsx#L13)
  - [L117](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/alpha-slider.tsx#L117)
- [packages/components/color-picker/src/color-selector-eye-dropper.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/color-selector-eye-dropper.tsx)
  - [L17](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/color-selector-eye-dropper.tsx#L17)
  - [L41](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/color-selector-eye-dropper.tsx#L41)
- [packages/components/color-picker/src/color-selector-swatches.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/color-selector-swatches.tsx)
  - [L65](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/color-selector-swatches.tsx#L65)
- [packages/components/color-picker/src/use-color-selector.ts](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts)
  - [L54](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L54)
  - [L203](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L203)
  - [L247](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L247)
  - [L265](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L265)
  - [L276](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L276)
  - [L291](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L291)
  - [L314](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L314)
  - [L347](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L347)
  - [L370](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L370)
  - [L416](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L416)
  - [L419](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L419)
  - [L451](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L451)
  - [L473](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L473)
  - [L520](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L520)
  - [L529](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L529)
  - [L544](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-selector.ts#L544)
- [packages/components/color-picker/src/use-color-slider.ts](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts)
  - [L148](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L148)
  - [L171](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L171)
  - [L178](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L178)
  - [L185](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L185)
  - [L209](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L209)
  - [L238](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L238)
  - [L248](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L248)
  - [L256](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-color-slider.ts#L256)
- [packages/components/color-picker/src/use-saturation-slider.ts](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts)
  - [L177](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L177)
  - [L201](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L201)
  - [L212](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L212)
  - [L219](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L219)
  - [L233](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L233)
  - [L256](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L256)
  - [L266](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L266)
  - [L274](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/color-picker/src/use-saturation-slider.ts#L274)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by 000000armor** [comment]
Hi @taroj1205 @hirotomoyamada! Please, let me work on this one.

**Comment by taroj1205** [comment]
Hi @000000armor,
Thank you for commenting.

I will assign it to you now.
Good luck!
