### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/input`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1027]
package: @yamada-ui/input

### Description
`@yamada-ui/input` has a test coverage of less than 80%. We will enhance it to above 80%.

### Target files
- [packages/components/input/src/input-addon.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/input/src/input-addon.tsx)
  - [L19](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/input/src/input-addon.tsx#L19)
  - [L57](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/input/src/input-addon.tsx#L57)
  - [L70](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/input/src/input-addon.tsx#L70)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by JauneBrillant** [comment]
@hirotomoyamada 
- hello!
- May I work on this issue?

**Comment by hirotomoyamada** [comment]
@JauneBrillant 

Hi, thanks for the comment!

Yes, please!

**Comment by hirotomoyamada** [comment]
Fixed
