### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/stepper`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1035]
package: @yamada-ui/stepper

### Description
`@yamada-ui/stepper` has a test coverage of less than 80%. We will enhance it to above 80%.

### Target files
- [packages/components/stepper/src/use-steps.ts](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/stepper/src/use-steps.ts)
  - [L9](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/stepper/src/use-steps.ts#L9)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by JauneBrillant** [comment]
@hirotomoyamada 
may I work on this issue ?

**Comment by hirotomoyamada** [comment]
@JauneBrillant 

Hi, thanks for the comment!

Yes, pls!

**Comment by JauneBrillant** [comment]
@hirotomoyamada 
The target file isn't actually being used, so testing this section is unnecessary. Confirmation of its non-usage was done by verifying that it's not being referenced.

There's a custom hook called useStep in packages/components/stepper/src/use-stepper.ts, which seems to be serving as a substitute.

**Comment by JauneBrillant** [comment]
Here are the options:

1. Do nothing - It feels uncomfortable to keep encountering this issue in the coverage tests, but we leave the code as it is.

2. Delete packages/components/stepper/src/use-steps.ts and remove unused import statements in packages/components/stepper/src/index.ts: This option removes the unused file and import statements, which should resolve the coverage test issue.

3. Separate the useStep custom hook in packages/components/stepper/src/use-stepper.ts into a separate file named use-step.ts, and delete the existing use-steps: This option splits the useStep hook into its own file while removing the unused use-steps file.

4. Another option that I haven't thought of!

**Comment by setodeve** [comment]
@JauneBrillant 

Thank you for your comments.

There may be some misunderstandings regarding the use of `useStep` and `useSteps`. 

Each of these custom hooks has a specific role:
`useStep`: This is an internally used custom hook.
`useSteps`: This custom hook is used for customizing the Step component.

For `useSteps`, you can find examples of its usage at https://yamada-ui.com/components/navigation/stepper#customize-steps.

Although several options have been suggested, there is no need to split or delete `useSteps`.

At this time, it is necessary to write test codes including `useSteps`.

**Comment by JauneBrillant** [comment]
@setodeve 

Thank you for explaining!
I completely misunderstood. I'm gonna write test code including `use-steps`!
