### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/table`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1036]
package: @yamada-ui/table

### Description
`@yamada-ui/table` has a test coverage of less than 80%. We will enhance it to above 80%.

### Target files
- [packages/components/table/src/paging-table.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/table/src/paging-table.tsx)
  - [L137](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/table/src/paging-table.tsx#L137)
- [packages/components/table/src/tfoot.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/table/src/tfoot.tsx)
  - [L10](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/table/src/tfoot.tsx#L10)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by atsushi729** [comment]
Hi, can I contribute this issue??

**Comment by hirotomoyamada** [comment]
@atsushi729 

Hi, thanks for the comment!

Yes, please!
