### ISSUE TITLE
`Legend` component display is broken on mobile

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1069]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.0

### Description

When there are many elements, the `Legend` component display is broken on mobile.

![localhost_3000_ja_components_feedback_line-chart](https://github.com/yamada-ui/yamada-ui/assets/84060430/72454d86-236d-43e3-a8b6-368761fa2a9e)

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

Chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by quantumshiro** [comment]
Is arranging each legend vertically, one after another, the correct approach to solving this issue?

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment!

I was thinking `overflow: auto` or `flex-wrap: wrap`. The basics are horizontal scrolling or wrapping.

**Comment by hirotomoyamada** [comment]
@quantumshiro 

Hi, thanks for the comment!

I was thinking `overflow: auto` or `flex-wrap: wrap`. The basics are horizontal scrolling or wrapping.

**Comment by quantumshiro** [comment]
It has not been take by anyone yet?

**Comment by hirotomoyamada** [comment]
@quantumshiro 

Yes.
