### ISSUE TITLE
If a theme is applied, use the theme's token in the `NumberInput` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1085]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.0

### Description

Currently, styling values in components ignore theme tokens. If a theme is applied, you should use the theme's token.

Yamada UI's style system provides fallback functions. If the value of the token in the first argument does not exist, it returns the second argument, the fallback value.

```diff
display: "flex",
flexDirection: "column",
position: "absolute",
top: "0",
insetEnd: "0px",
margin: "1px",
height: "calc(100% - 2px)",
- zIndex: "1",
+ zIndex: "fallback(yamcha, 1)"
...styles.addon,
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by saka-git** [comment]
こちらのイシュー担当したいです！

**Comment by KenyaMasuko** [comment]
OK! Good luck!（私の会社の同僚です）
