### ISSUE TITLE
If a theme is applied, use the theme's token in the `Breadcrumb` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1093]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.0

### Description

Currently, styling values in components ignore theme tokens. If a theme is applied, you should use the theme's token.

Yamada UI's style system provides fallback functions. If the value of the token in the first argument does not exist, it returns the second argument, the fallback value.

```diff
/**
 * The left and right margin applied to the separator.
 *
- * @default 'sm'
+ * @default '2'
 */
gap?: CSSUIProps["mx"]
```

```diff
const {
  className,
  children,
  separator = "/",
-  gap = "0.5rem",
+  gap = "fallback(2, 0.5rem)",
  listProps,
  ...rest
} = omitThemeProps(mergedProps)
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by Tomoya-Matsubara** [comment]
Hi! May I work on this issue?

**Comment by hirotomoyamada** [comment]
@Tomoya-Matsubara 

Hi, thanks for the comment!

Yes, please!

I'll assign this issue to you, Good luck!
