### ISSUE TITLE
If a theme is applied, use the theme's token in the `NoticeProvider` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1099]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.0

### Description

Currently, styling values in components ignore theme tokens. If a theme is applied, you should use the theme's token.

Yamada UI's style system provides fallback functions. If the value of the token in the first argument does not exist, it returns the second argument, the fallback value.

```diff
export const NoticeProvider: FC<NoticeProviderProps> = ({
  variants,
-  gap = "1rem",
+  gap = "fallback(4, 1rem)",
  appendToParentPortal,
  containerRef,
}) => {
```

```diff
const css: CSSUIObject = {
  position: "fixed",
-  zIndex: 160,
+  zIndex: "fallback(zarbon, 160)",
  pointerEvents: "none",
  display: "flex",
  flexDirection: "column",
  margin: gap,
  gap,
  top,
  bottom,
  right,
  left,
}
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by SatooRu65536** [comment]
@hirotomoyamada 
Hi! Can I contribute this issue?

**Comment by hirotomoyamada** [comment]
@SatooRu65536 

Hi, thanks the comment!

Yes, please.

I'll assign this issue to you.
