### ISSUE TITLE
chart axisLabel 

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#1105]
### Description

Additional function to display axisLabel.
- `AreaChart`
- `LineChart`
- `BarChart`

https://mantine.dev/charts/area-chart/#axis-labels

### Problem Statement/Justification

Necessary to specify what the value is.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by 000000armor** [comment]
Hi @108yen, can I work on this one?

**Comment by 108yen** [comment]
@000000armor 
Yes, please!
I assinged you!
If you have any questions about implementation, ask.

**Comment by hirotomoyamada** [comment]
Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.
