### ISSUE TITLE
Add props to `Image` component to show `Skeleton` while image is loading.

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#1140]
### Description

Add props to `Image` component to show `Skeleton` while image is loading.

### Problem Statement/Justification

There is currently no props to show a `Skeleton` for `Image` component while it is loading.

### Alternatives

```tsx
<Skeleton isLoaded={isLoaded} fadeDuration={2}>
  <Image
    src="https://dragon-ball-official.com/assets/img/intro/intro_1.png"
    size="xl"
    onLoad={() => setIsLoaded(true)}
  />
</Skeleton>
```

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by hirotomoyamada** [comment]
@taroj1205 

Hi, thanks for the issue.

Are you supposed to put @yamada-ui/skeleton inside @yamada-ui/image? and?

**Comment by taroj1205** [comment]
> @taroj1205
> 
> Hi, thanks for the issue.
> 
> Are you supposed to put @yamada-ui/skeleton inside @yamada-ui/image? and?

Next UI has this built in.
https://nextui.org/docs/components/image#animated-loading
Yes, putting `@yamada-ui/skeleton` inside `@yamada-ui/image` could be one possible way, but I think users should also be able to use their components as loading skeleton.

**Comment by hirotomoyamada** [comment]
@taroj1205 

I support the idea of implementing `SkeletonImage` in `@yamada-ui/skeleton`.
