### ISSUE TITLE
Add prop to `ScrollArea` scrolling direction

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#1145]
### Description

We should add a prop to allow `ScrollArea` to be scrolled horizontally.

### Problem Statement/Justification

The `ScrollArea` currently only allows vertical scrolling, but there might be some cases where you want horizontal scrolling.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by hirotomoyamada** [comment]
@taroj1205 

Hi, thanks for the issue.

There are no direct props like in this issue, but I feel like it was possible to scroll horizontally.

**Comment by taroj1205** [comment]
I see, I have just tested and it is indeed possible with `overflowX="auto"`.
