### ISSUE TITLE
`className` is not assigned to `Cursor` in chart

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#1193]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.3

### Description

`use-chart-tooltip.ts`
```diff ts
      cursor: {
-        className: cursorClassName,
+        className: cx("ui-chart__cursor", cursorClassName),
      },
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by xBlackTea** [comment]
i wanna do it

**Comment by 108yen** [comment]
@xBlackTea 
Thank you, comment.
I'll assign this issue to you.
