### ISSUE TITLE
Add JSDoc to `Portal` component.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1220]
### Description

JSDoc is currently missing from the `Portal` component.

### Problem Statement/Justification

Since JSDoc exists for other components, we should also add `Portal` component.

### Proposed Solution or API

```diff
+ /**
+ * `Portal` is a component that renders elements outside of the current `DOM` hierarchy.
+ *
+ * @see Docs https://yamada-ui.com/components/other/portal
+ */
export const Portal = ({
  containerRef,
  appendToParentPortal = true,
  isDisabled,
  children,
}: PortalProps) => {
  if (isDisabled) return children

  return containerRef ? (
    <ContainerPortal
      containerRef={containerRef}
      {...{ appendToParentPortal, children }}
    />
  ) : (
    <DefaultPortal {...{ appendToParentPortal, children }} />
  )
}
```

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by KekmaTime** [comment]
@hirotomoyamada i can work on this issue

**Comment by Tay3052** [comment]
I want to join it.

**Comment by hirotomoyamada** [comment]
@KekmaTime 

Hi, thanks for the comment.

Yes, pls.

I'll assign this issue to you. Good luck!
