### ISSUE TITLE
`main` tag is used in `Popover` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1234]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.4

### Description

There should be only one `main` tag in a document.

https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

```diff
export const PopoverBody = forwardRef<PopoverBodyProps, "main">(
  ({ className, ...rest }, ref) => {
    const { styles } = usePopover()

    const css: CSSUIObject = {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      ...styles.body,
    }

    return (
-      <ui.main
+      <ui.div
        ref={ref}
        className={cx("ui-popover__body", className)}
        __css={css}
        {...rest}
      />
    )
  },
)
```

**Comment by KekmaTime** [comment]
@hirotomoyamada i can work on this issue

**Comment by hirotomoyamada** [comment]
@KekmaTime 

Hi, thanks for the comment!

Yes, pls!
