### ISSUE TITLE
`main` tag is used in `Modal` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1235]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.4

### Description

There should be only one `main` tag in a document.

https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

```diff
export const ModalBody = forwardRef<ModalBodyProps, "main">(
  ({ className, __css, ...rest }, ref) => {
    const { styles, scrollBehavior } = useModal()

    const css: CSSUIObject = {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      overflow: scrollBehavior === "inside" ? "auto" : undefined,
      ...(__css ? __css : styles.body),
    }

    return (
-      <ui.main
+      <ui.div
        ref={ref}
        className={cx("ui-modal__body", className)}
        __css={css}
        {...rest}
      />
    )
  },
)
```

**Comment by eda-saizaku** [comment]
@hirotomoyamada 
I'll try this issue!

**Comment by hirotomoyamada** [comment]
@eda-saizaku

Thanks for the comment!

Yes, pls.
