### ISSUE TITLE
`TextStyles` and  `LayerStyles` of the wrong type

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#1303]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

`TextStyles` and  `LayerStyles` of the wrong type.
Callback functions are not accepted. Only objects should be accepted.

`theme.types.ts`
```diff ts
-export type LayerStyles = Record<string, UIStyle>
-export type TextStyles = Record<string, UIStyle>
+export type LayerStyles = Record<string, CSSUIObject>
+export type TextStyles = Record<string, CSSUIObject>
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by Yutan0423** [comment]
@108yen Hi! Can I work on this issue?

**Comment by 108yen** [comment]
@Yutan0423 
Yes, please!
I assign you.
