### ISSUE TITLE
There is duplicate processing in `useCheckbox`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1314]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

`pickObject` is done 4 times in `useCheckbox`. This should be assigned to a variable and reused.

```ts
const formControlProps = pickObject(
  rest,
  getFormControlProperties({ omit: ["aria-readonly"] }),
)
```

```diff
const getContainerProps: UIPropGetter = useCallback(
  (props = {}, ref = null) => ({
-     ...pickObject(
-       rest,
-       getFormControlProperties({ omit: ["aria-readonly"] }),
-     ),
+   ...formControlProps,
    ...props,
    ref: mergeRefs(ref, (el: HTMLElement | undefined) => {
      if (el) setIsLabel(el.tagName === "LABEL")
    }),
    "data-checked": dataAttr(checked),
    onClick: handlerAll(props.onClick, () => {
      if (isLabel) return

      inputRef.current?.click()

      requestAnimationFrame(() => inputRef.current?.focus())
    }),
  }),
  [checked, isLabel, rest],
)
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by GensIto** [comment]
@hirotomoyamada 
can I work on this issue??

**Comment by hirotomoyamada** [comment]
@GensIto 

Hi, thanks for the comment!

Yes, pls.

I'll assign this issue to you. Good luck!!
