### ISSUE TITLE
`Image` has unnecessary `omitObject`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1321]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

```diff
let {
  fallback,
  src,
  srcSet,
  loading,
  ignoreFallback,
  crossOrigin,
  className,
  fallbackStrategy = "beforeLoadOrError",
+ onError,
+ onLoad,
  referrerPolicy,
  size: boxSize,
  fit: objectFit,
  ...rest
} = props
```

```diff
- const status = useImage({ ...props, crossOrigin, ignoreFallback })
+ const status = useImage({ ...props, ignoreFallback })
```

```diff
- {...(ignoreFallback ? rest : omitObject(rest, ["onError", "onLoad"]))}
+ {...(ignoreFallback ? { ...rest, onError, onLoad } : rest)}
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by Eiji-Kudo** [comment]
I want to work on this!

**Comment by hirotomoyamada** [comment]
@Eiji-Kudo 

Hi, thanks for the comment!

Yes, pls.
