### ISSUE TITLE
`Indicator` has unnecessary `omitObject`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1322]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

Integrate `omitObject` handling with `omitThemeProps`.

```diff
let {
  className,
  inline = false,
  placement = "top-right",
  offset = 0,
  label,
  overflowCount = 99,
  showZero = true,
  children,
  isDisabled,
  containerProps,
  ping,
  pingColor = "var(--ui-ping)",
  pingDuration = "1.4s",
  pingCount = "infinite",
  pingScale = 1.8,
  ...rest
- } = omitThemeProps(mergedProps)
+ } = omitThemeProps(mergedProps, ["withBorder"])
```

```diff
<ui.div
  ref={ref}
  className={cx("ui-indicator__icon", className)}
  __css={css}
-  {...omitObject(rest, ["withBorder"])}
+  {...rest}
>
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by sacky3105** [comment]
I would like to challenge this issue.

**Comment by hirotomoyamada** [comment]
@sacky3105 

Hi, thanks for the comment!

Yes, pls.

I'll assign this issue to you. Good luck!!
