### ISSUE TITLE
`NativeTable` has unnecessary `omitObject`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1325]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

Integrate `omitObject` handling with `omitThemeProps`.

```diff
- const { className, layout, ...rest } = omitThemeProps(mergedProps)
+ const { className, layout, ...rest } = omitThemeProps(mergedProps, ["withBorder", "withColumnBorders", "highlightOnHover"])
```

```diff
<ui.table
  ref={ref}
  className={cx("ui-table", className)}
  __css={css}
-   {...omitObject(rest, [
-     "withBorder",
-     "withColumnBorders",
-     "highlightOnHover",
-   ])}
+   {...rest}
/>
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by teru12012000** [comment]
I would like to challenge this issue.

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment.

Yes, pls.
