### ISSUE TITLE
`MenuOptionGroup` has unnecessary `omitObject`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1328]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

Integrate `omitObject` handling with `omitThemeProps`.

```diff
{
  className,
+ value: valueProp,
  defaultValue,
+ onChange: onChangeProp,
  type,
  children,
  ...rest
}: MenuOptionGroupProps<Y>,
```

```diff
const [value, setValue] = useControllableState({
- ...rest,
+ value: valueProp,
  defaultValue,
+ onChange: onChangeProp,
})
```

```diff
<MenuGroup
  ref={ref}
  className={cx("ui-menu__item--group--option", className)}
- {...omitObject(rest, ["value", "onChange"])}
+ {...rest}
>
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by jasonmokk** [comment]
Hi, I'd like to work on this one please.

**Comment by hirotomoyamada** [comment]
@jasonmokk 

Hi, thanks for the comment!

Yes, pls.
