### ISSUE TITLE
`Table` has unnecessary `omitObject`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1329]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

Integrate `omitObject` handling with `omitThemeProps`.

```diff
const {
  className,
  withFooter = false,
  theadProps,
  tbodyProps,
  tfootProps,
  checkboxProps,
  layout,
  children,
  ...computedProps
- } = omitThemeProps(mergedProps)
+ } = omitThemeProps(mergedProps, ["highlightOnSelected", "highlightOnHover", "withBorder", "withColumnBorders"])
```

```diff
const { getTableProps, ...rest } = useTable<Y>({
- ...omitObject(computedProps, [
-   "highlightOnSelected",
-   "highlightOnHover",
-   "withBorder",
-   "withColumnBorders",
- ]),
+ ...computedProps,
  checkboxProps: { colorScheme, ...checkboxProps },
})
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by Eiji-Kudo** [comment]
I'll work on this issue

**Comment by hirotomoyamada** [comment]
@Eiji-Kudo 

Hi, thanks for the comment!

Yes, pls.
