### ISSUE TITLE
`Textarea` has unnecessary `omitObject`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1330]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.7

### Description

```diff
- const [styles, mergedProps] = useComponentStyle("Textarea", props)
+ const [{ h, height, minH, minHeight, maxH, maxHeight, ...styles }, mergedProps] = useComponentStyle("Textarea", props)
```

```diff
if (rows || autosize) {
- css = omitObject(styles, [
-   "h",
-   "height",
-   "minH",
-   "minHeight",
-   "maxH",
-   "maxHeight",
- ])
+ css = styles
} else {
- css = styles
+ css = { h, height, minH, minHeight, maxH, maxHeight, ...styles }
}
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by dovicie** [comment]
Hi @hirotomoyamada , can I work on this one?

**Comment by hirotomoyamada** [comment]
@dovicie 

Hi, thanks for the comment!

Yes, pls.

I'll assign this issue to you. Good luck!
