### ISSUE TITLE
`thumb` of `Slider` appears above `Autocomplete` pop-up

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#1385]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.8

### Description

`thumb` of `Slider` appears above the pop-up where the `Autocomplete` item is displayed.

https://github.com/yamada-ui/yamada-ui/assets/9676316/83d11d50-3ff1-4fbb-8f52-612d6a92f6a8

I think the reason is that `thumb` of `Slider` has `zIndex` set and `Autocomplete` does not have `zIndex` set.
`slider.ts`
```ts
thumb: ({ theme: t, colorMode: m, orientation: o }) => ({
      position: "absolute",
      zIndex: "yamcha",
      display: "flex",
```

 `zIndex` should be set to `styles.group` so that it takes precedence over `thumb` in the `Slider`.
`autocomplete-option-groupe.tsx`
```tsx
        <ui.ul
          {...getGroupProps({}, ref)}
          className="ui-autocomplete__item__group"
          __css={{ h, minH, ...styles.group }}
        >
          {children}
        </ui.ul>
```

### Steps to Reproduce

1. Go to https://yamada-ui.com/examples/playground
2. Click on Model form
3. You can see that the `thumb` of `Slider` appears above the pop-up

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

I think `Select` and `NativeSelect` have the same bug.

**Comment by hirotomoyamada** [comment]
`Select` and `Autocomplete` inherit the `Menu` style. Since we are using `Popover` internally, it should be the same `z-index` as `Popover`.
