### ISSUE TITLE
`AvatarBadge`内のクラス名の修正

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#1408]
### どのパッケージに問題がありますか？

@yamada-ui/react

### パッケージのバージョン

1.3.9

### 概要

Yamada UIのクラス名の命名規則はBEMに従っていますが、`AvatarBadge`内の`ui-avatar__badge__ping`のクラス名がそれに違反しています。

- `ui-avatar__ping`に修正してください。
- `changeset`は`major`で作ってください。
- v2.0.0でリリースする予定なので`main`ブランチではなく`v2.0`のブランチから新しくブランチを派生させて、`v2.0`のブランチ向けのPull Requestを作成してください。

### 再現手順

1. '...'に行きます。
2. '...'をクリックします。
3. '...'までスクロールします。
4. エラーを確認します。

### ブラウザ

None

### OS

- [X] macOS
- [X] Windows
- [X] Linux

### まさか、問題の修正方法をご存知ですか？

はい

### この問題の修正に参加し、修正を含むプルリクエストを作成しますか？

None

**Comment by EndoTaishi** [comment]
こんにちは。
こちらに取り組んでも良いでしょうか？

**Comment by illionillion** [comment]
> こんにちは。 こちらに取り組んでも良いでしょうか？

@EndoTaishi こんにちわ！
是非取り組んでください！！

**Comment by illionillion** [comment]
このイシューはクローズしました。
