### ISSUE TITLE
Correct class name in `Autocomplete`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#1409]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Corrected the following class names according to BEM

- `ui-autocomplete__item__icon`
  - fix to `ui-autocomplete__item-icon`
- `ui-autocomplete__item__group-label`
  - fix to `ui-autocomplete__group-label`
- `ui-autocomplete__item__group`
  - fix to `ui-autocomplete__group`
- `ui-autocomplete__field__input`
  - fix to `ui-autocomplete__input`

Please be careful of the following when working

- Create the changeset with `major`. 
- Please derive a new branch from the `v2.0` branch and create a pull request for the `v2.0` branch, not the `main` branch, as we plan to release the product in v2.0.0.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by sacky3105** [comment]
I would like to challenge this issue.

**Comment by hirotomoyamada** [comment]
@sacky3105 

Hi, thanks for the comment.

It looks like a PR has already been created :(

**Comment by illionillion** [comment]
This issue is closed.
