### ISSUE TITLE
Fix class names in `Breadcrumb`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#1410]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Corrected the following class names according to BEM

- `ui-breadcrumb__item__separator`
  - fixed to `ui-breadcrumb__separator`
- `ui-breadcrumb__item__ellipsis`
  - fixed to `ui-breadcrumb__ellipsis`

Please be careful of the following when working

Create the changeset with `major`.
Please derive a new branch from the `v2.0` branch and create a pull request for the `v2.0` branch, not the `main` branch, as we plan to release the product in v2.0.0.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by darkcat666** [comment]
I would like to challenge this issue.

**Comment by illionillion** [comment]
This issue is closed.
