### ISSUE TITLE
Correct class name in `Carousel`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#1481]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Corrected the following class names according to BEM

- `ui-carousel__indicators__indicator`
  - fix to `ui-carousel__indicator`
- `ui-carousel__slide__inner`
  - fix to `ui-carousel__slide-inner`
- `ui-carousel__sliders__inner`
  - fix to `ui-carousel__sliders-inner`

Create the changeset with `major`.
Please derive a new branch from the `v2.0` branch and create a pull request for the `v2.0` branch, not the `main` branch, as we plan to release the product in `v2.0.0`.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by illionillion** [comment]
Fix the test code if necessary.

**Comment by aojunhao123** [comment]
> Fix the test code if necessary.

got it
