### ISSUE TITLE
Research alert accessibility 

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1486]
### 概要

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/alert/) and [this article](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/) and research alert accessibility

modify component if necessary

### 問題の主張/正当化

none

### この機能の実装に参加し、実装を含むプルリクエストを作成しますか？

None

**Comment by nakayan5** [comment]
@GensIto 
assign you to this issue too.
please comment if you confirm.

**Comment by setodeve** [comment]
#### WAI-ARIA Roles, States, and Properties

- [x] **Alert Role:**
  - [x] The alert message element has `role="alert"`.

**Comment by setodeve** [comment]
I think [Alert and Message Dialogs Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/) match to `Dialog` and does not match to `Alert`.

**Comment by nakayan5** [comment]
@setodeve 
double check is done

**Comment by nakayan5** [comment]
@setodeve 
Since there does not seem to be anything to correct at present, I will close this issue.
