### ISSUE TITLE
Research breadcrumb accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1487]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/) and research breadcrumb accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by setodeve** [comment]
#### General Requirements
- [x] **Navigation Landmark:**
  - [x] Breadcrumb trail is contained within a `navigation` landmark region.

- [ ] **Landmark Region Label:**
  - [ ] The navigation landmark region is labeled using `aria-label` or `aria-labelledby`.

- [x] **Current Page Indicator:**
  - [x] The link to the current page has `aria-current="page"`.

**Comment by nakayan5** [comment]
@setodeve 
> The link to the current page has aria-current="page".

Is this fulfilled?

**Comment by setodeve** [comment]
@nakayan5 
I thought of it is fulfilled by the following line.
https://github.com/yamada-ui/yamada-ui/blob/9279268e3a74629b0d23bd93119cf642e910c71a/packages/components/breadcrumb/src/breadcrumb.tsx#L333

**Comment by nakayan5** [comment]
@setodeve 
lets create issue

**Comment by setodeve** [comment]
Created Issue #1726
