### ISSUE TITLE
Research button accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1488]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/button/) and research button accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by nakayan5** [comment]
@GensIto 
assign you to this issue too.
please comment if you confirm.

**Comment by setodeve** [comment]
### Accessibility Checklist for Button Pattern

#### General Requirements
- [ ] **Button Role:**
  - [ ] The button element has `role="button"`.

- [ ] **Accessible Label:**
  - [ ] The button has an accessible label computed from its text content, `aria-labelledby`, or `aria-label`.

- [ ] **Button Description:**
  - [ ] If a description of the button's function is present, the button element has `aria-describedby` set to the ID of the element containing the description.

- [ ] **Disabled State:**
  - [ ] When the action associated with a button is unavailable, the button has `aria-disabled="true"`.

#### Toggle Button Specific Requirements
- [ ] **Toggle State:**
  - [ ] The button has an `aria-pressed` attribute.
  - [ ] When toggled on, `aria-pressed` is set to `true`.
  - [ ] When toggled off, `aria-pressed` is set to `false`.
  - [ ] The label does not change when the state changes.

#### Menu Button Specific Requirements
- [ ] **Menu Button Role:**
  - [ ] The button has `aria-haspopup` set to either `menu` or `true`.

#### Keyboard Interaction
- [ ] **Focus Behavior:**
  - [ ] When the button has focus:
    - [ ] `Space` activates the button.
    - [ ] `Enter` activates the button.

- [ ] **Post-Activation Focus:**
  - [x] If the button opens a dialog, focus moves inside the dialog.
  - [ ] If the button closes a dialog, focus typically returns to the button that opened the dialog.
  - [x] If the button's action does not dismiss the current context, focus remains on the button.
  - [ ] If the button's action indicates a context change, focus moves to the starting point for that action.
  - [ ] If activated with a shortcut key, focus usually remains in the context from which the shortcut key was activated.

**Comment by nakayan5** [comment]
@setodeve 

> The button element has role="button".

botton tags don't require a role button

**Comment by nakayan5** [comment]
@setodeve 
button tag already contains role= 'button
Other checks have been fulfilled.

lets create issue

**Comment by setodeve** [comment]
Created Issue #1737
