### ISSUE TITLE
Research carousel accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1489]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/) and research carousel accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by nakayan5** [comment]
@GensIto 
assign you to this issue too.
please comment if you confirm.

**Comment by setodeve** [comment]
#### General Requirements
- **Visible Labels:**
  - [ ] Carousel container has an accessible label using `aria-labelledby` or `aria-label`.
  - [x] Label does not include the word "carousel".

- **Roles and Descriptions:**
  - [ ] Carousel container has `role="region"` or `role="group"`.
  - [ ] `aria-roledescription="carousel"` is set on the carousel container.
  - [ ] Each slide container has `role="group"` with `aria-roledescription="slide"`.

#### Rotation Control
- **Rotation Control Button:**
  - [x] Exists as a native button element or implements the button pattern.
  - [ ] Accessible label provided by `aria-label` or inner text.
  - [ ] Label changes based on action (e.g., "Stop slide rotation" or "Start slide rotation").
  - [x] Button does not use `aria-pressed`.

#### Slide Navigation
- **Next and Previous Slide Controls:**
  - [x] Exist as native button elements or implement the button pattern.
  - [x] Styled as arrows.
  - [ ] Do not move focus when activated.

- **Slide Picker Controls (if present):**
  - [x] Group of elements, often styled as small dots or tabs.
  - [x] Each control is a native button element or implements the button pattern.
  - [ ] Accessible name indicates the slide it will display.
  - [ ] Current slide control has `aria-disabled="true"`.

#### Keyboard Interaction
- **Tab and Shift + Tab Navigation:**
  - [x] Moves focus through carousel interactive elements.
  - [ ] Rotation control is the first element in the tab sequence.

- **Automatic Slide Rotation:**
  - [ ] Stops when any carousel element receives keyboard focus.
  - [ ] Does not resume unless the user activates the rotation control.
  - [x] Stops when the mouse hovers over the carousel.

#### WAI-ARIA Implementation
- **Basic Carousel Elements:**
  - [ ] Carousel container includes all components, with `role="region"` or `role="group"`.
  - [ ] Rotation, next slide, and previous slide controls are native button elements or implement the button pattern.
  - [ ] Each slide container has `role="group"` with `aria-roledescription="slide"`.
  - [ ] Each slide has an accessible name using `aria-labelledby` or `aria-label`.
  - [ ] Wrapper element for slides has `aria-atomic="false"` and `aria-live="off"` if rotating, `aria-live="polite"` if not.

**Comment by nakayan5** [comment]
@setodeve 
double check is done

**Comment by nakayan5** [comment]
@setodeve 
lets create issue

**Comment by setodeve** [comment]
created Issue #1728
