### ISSUE TITLE
Research checkbox accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1492]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/) and research checkbox accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by koralle** [comment]
Several practices in the feed pattern can be applied to the [Checkbox](https://yamada-ui.com/components/forms/checkbox) component.

---

**Comment by koralle** [comment]
## Double-State Checkbox

The behavior of the component is the same as the current `Checkbox` component.

## Tri-State Checkbox

To further enhance accessibility, it is necessary to support Tri-State Checkbox.  
It might be necessary to implement additional components.

### Tri-State Checkbox (1/2)

![tri-state-checkbox_1](https://github.com/yamada-ui/yamada-ui/assets/33865215/6919683d-e8a4-480e-859e-164bc8635a6d)

### Tri-State Checkbox (2/2)

![tri-state-checkbox_2](https://github.com/yamada-ui/yamada-ui/assets/33865215/92061571-ff8e-4686-8ecc-abcea35e3766)

## Keyboard Interaction

* [ ] When the checkbox has focus, pressing the `Space` key changes the state of the checkbox.

## WAI-ARIA Roles, States, and Properties

* [ ] The checkbox has role `checkbox`.
* [ ] The `checkbox` has an accessible label provided by one of the following:
  * [ ] Visible text content contained within the element with role `checkbox`.
  * [ ] A visible label referenced by the value of `aria-labelledby` set on the element with role `checkbox`.
  * [ ] `aria-label` set on the element with role `checkbox`.
* [ ] When checked, the checkbox element has state `aria-checked` set to `true`.
* [ ] When not checked, it has state `aria-checked` set to `false`.
* [ ] When partially checked, it has state `aria-checked` set to `mixed`.
* [ ] If a set of checkboxes is presented as a logical group with a visible label, the checkboxes are included in an element with role `group` that has the property `aria-labelledby` set to the ID of the element containing the label.
* [ ] If the presentation includes additional descriptive static text relevant to a checkbox or checkbox `group`, the checkbox or checkbox group has the property `aria-describedby` set to the ID of the element containing the description.

**Comment by nakayan5** [comment]
@koralle 
Have you created an issue?
I couldn't find it.
