### ISSUE TITLE
Research dialog (modal)  accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1494]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/) and research dialog-modal accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by GensIto** [comment]
@nakayan5 
Please assign me

**Comment by setodeve** [comment]
#### Basic Checks
- [ ] Component has `role="dialog"`.
- [ ] Component has `aria-modal="true"`.
- [ ] `aria-labelledby` or `aria-label` is set.

#### Initial Focus
- [ ] Initial focus is set on the first focusable element inside the dialog.
- [ ] Uses `tabindex="-1"` where appropriate.

#### Keyboard Interaction
- [ ] Tab key moves focus to the next element inside the dialog.
- [ ] Shift + Tab key moves focus to the previous element inside the dialog.
- [ ] Escape key closes the dialog.

#### Focus Return
- [ ] Focus returns to the invoking element when the dialog closes.

#### Close Button
- [ ] Dialog includes a visible close button.

#### Visual Styling
- [ ] Content outside the dialog is visually obscured.

#### Special Role (For AlertDialog)
- [ ] `role="alertdialog"` is used appropriately.

**Comment by setodeve** [comment]
Created Issue #1686

**Comment by nakayan5** [comment]
@koralle 
please double check
