### ISSUE TITLE
Research disclosure accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1495]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) and research disclosure accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by GensIto** [comment]
@nakayan5 
Please assign me

**Comment by koralle** [comment]
Several practices in the feed pattern can be applied to the [Accordion](https://yamada-ui.com/components/disclosure/accordion).

## Keyboard Interaction
When the disclosure control has focus:

* [ ] `Enter`: activates the disclosure control and toggles the visibility of the disclosure content.
* [ ] `Space`: activates the disclosure control and toggles the visibility of the disclosure content.

## WAI-ARIA Roles, States, and Properties
* [ ] The element that shows and hides the content has role [button](https://w3c.github.io/aria/#button).
* [ ] When the content is visible, the element with role button has [aria-expanded](https://w3c.github.io/aria/#aria-expanded) set to true. When the content area is hidden, it is set to false.
* [ ] Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element that contains all the content that is shown or hidden.

**Comment by nakayan5** [comment]
@koralle
Can I close this issue ?

**Comment by setodeve** [comment]
> Several practices in the feed pattern can be applied to the [Accordion](https://yamada-ui.com/components/disclosure/accordion).
> 
> ## Keyboard Interaction
> When the disclosure control has focus:
> 
> * [ ]  `Enter`: activates the disclosure control and toggles the visibility of the disclosure content.
> * [ ]  `Space`: activates the disclosure control and toggles the visibility of the disclosure content.
> 
> ## WAI-ARIA Roles, States, and Properties
> * [x]  The element that shows and hides the content has role [button](https://w3c.github.io/aria/#button).
> * [ ]  When the content is visible, the element with role button has [aria-expanded](https://w3c.github.io/aria/#aria-expanded) set to true. When the content area is hidden, it is set to false.
> * [ ]  Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element that contains all the content that is shown or hidden.

already addressed.
https://github.com/yamada-ui/yamada-ui/issues/1930
