### ISSUE TITLE
Research menu button accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1502]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/) and research menu-button accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by illionillion** [comment]
- Keyboard Interaction
  - With focus on the button:
    - [ ] `Enter`: opens the menu and places focus on the first menu item.
    - [ ] `Space`: Opens the menu and places focus on the first menu item.
    - [ ] (Optional) `Down Arrow`: opens the menu and moves focus to the first menu item.
    - [ ] (Optional) `Up Arrow`: opens the menu and moves focus to the last menu item.
  - [ ] The keyboard behaviors needed after the menu is open are described in the [Menu and Menubar Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/).
- WAI-ARIA Roles, States, and Properties
  - [ ] The element that opens the menu has role [button](https://w3c.github.io/aria/#button).
  - [ ] The element with role button has [aria-haspopup](https://w3c.github.io/aria/#aria-haspopup) set to either menu or true.
  - [ ] When the menu is displayed, the element with role button has [aria-expanded](https://w3c.github.io/aria/#aria-expanded) set to true. When the menu is hidden, aria-expanded is set to false.
  - [ ] The element that contains the menu items displayed by activating the button has role [menu](https://w3c.github.io/aria/#menu).
  - [ ] Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element with role menu.
  - [ ] Additional roles, states, and properties needed for the menu element are described in the [Menu and Menubar Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/).

**Comment by nakayan5** [comment]
@yamada-ui/menu is applicable

**Comment by nakayan5** [comment]
@koralle 
please double check

**Comment by nakayan5** [comment]
> Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element with role menu.Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element with role menu.Optionally, the element with role button has a value specified for [aria-controls](https://w3c.github.io/aria/#aria-controls) that refers to the element with role menu.

its optionally, so I don't think we need to fix this one this time.
