### ISSUE TITLE
Research tooltip accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1511]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/) and research tooltip accessibility

modify component if necessary

### Problem Statement/Justification

none

### Alternatives

- [ ] #1634

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by nakayan5** [comment]
@yamada-ui/tooltip is applicable to this issue

**Comment by nakayan5** [comment]
@yamada-ui/tooltip probably does not satisfy all the checkmarks.

**Comment by nakayan5** [comment]
@taroj1205 
please double check

**Comment by taroj1205** [comment]
> @taroj1205 please double check

Yes, it does seems to not satisfy `WAI-ARIA Roles, States, and Properties`.

**Comment by nakayan5** [comment]
created issue
https://github.com/yamada-ui/yamada-ui/issues/1634
