### ISSUE TITLE
Research window splitter accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1514]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/) and research windowsplitter accessibility

modify component if necessary

### Problem Statement/Justification

none

### Alternatives

- [ ] #1633

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by nakayan5** [comment]
@yamada-ui/resizable is applicable to this issue

**Comment by nakayan5** [comment]
@illionillion 
please double check

**Comment by illionillion** [comment]
@nakayan5 
Checked.
The same item applied.
Do you want to correct the items whose checkboxes are not checked?

**Comment by nakayan5** [comment]
@illionillion 

> F6 (Optional): Cycle through window panes.

This is optional, so I don't think it's necessary.
I think aria-label is necessary.

@hirotomoyamada 
What do you think ?

**Comment by hirotomoyamada** [comment]
@nakayan5 

> F6 (Optional): Cycle through window panes.

This does not correspond

**Comment by nakayan5** [comment]
created issue
https://github.com/yamada-ui/yamada-ui/issues/1633
