### ISSUE TITLE
Fix class name in `indicator`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#1532]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Corrected the following class names according to BEM

- `ui-indicator__icon__ping`
  - fix to `ui-indicator__ping`

Create the changeset with `major`.
Please derive a new branch from the `v2.0` branch and create a pull request for the `v2.0` branch, not the `main` branch, as we plan to release the product in v2.0.0.

Fix the test code if necessary.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by jasonmokk** [comment]
Hello, may I work on this issue?

**Comment by illionillion** [comment]
> Hello, may I work on this issue?

Hello, of course.
I have assigned you.

**Comment by illionillion** [comment]
> @illionillion I didn't know that I have to tell you for assigning. I've already created PR, Is there any information to ask you assigning me, I've checked CONTRIBUTE.md, and README though? #1535

@16dango 

It is not mandatory to do so, but it is better to comment on the issue first to avoid creating a PR with the same content.
This time I will try to incorporate the PR you created earlier.

@jasonmokk 
Sorry, please try to work on another `good first issue`.

**Comment by illionillion** [comment]
> @illionillion Thank you for replying kindly and teach me how I should before working on the issue. I'll keep in mind that I should comment before working on it. And the test is failed so I'm trying to fit the problem, I'll tell you after all test is fine

@16dango 
The workflow will run automatically when approved by review.
Create a changelog file as described in `changeset`.

https://github.com/yamada-ui/yamada-ui/blob/main/CONTRIBUTING.md#steps-to-pr
https://github.com/changesets/changesets/tree/main/packages/cli

**Comment by illionillion** [comment]
This issue was closed.
