### ISSUE TITLE
Add accessibility section for `autocomplete`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#1540]
### Subject

accessibility section for `autocomplete`

#### Create an accessibility section referring to the links below
https://yamada-ui.com/components/disclosure/tabs/accessibility#aria-roles-and-attributes ( https://github.com/yamada-ui/yamada-ui/issues/1552 )
https://www.radix-ui.com/primitives/docs/components/accordion#accessibility
https://mantine.dev/core/autocomplete/#accessibility

#### Include the following content
* keboard interaction
* aria, tabindex property are supported

#### reference
https://github.com/yamada-ui/yamada-ui/issues/2050

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by hirotomoyamada** [comment]
Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.

**Comment by nakayan5** [comment]
related https://github.com/yamada-ui/yamada-ui/issues/2050
