### ISSUE TITLE
Add accessibility section for `checkbox`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#1542]
### Subject

accessibility section for `checkbox`

#### Create an accessibility section using the link below
https://yamada-ui.com/components/disclosure/tabs/accessibility#aria-roles-and-attributes
https://www.radix-ui.com/primitives/docs/components/checkbox#accessibility
https://mui.com/material-ui/react-checkbox/#accessibility
https://mantine.dev/core/checkbox/#accessibility

#### Include the following content
* keyboard interaction
* aria, role, tabindex property are supported
* link for W3C reference(https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/)
### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by Haru-0001** [comment]
As soon as `Accordion` and `Radio` are done, we will get started.
