### ISSUE TITLE
Add accessibility section for `color-picker`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#1543]
### Subject

accessibility section for `color-picker`

#### this issue include file below
 - use-color-slider.ts
 - use-saturation-slider.ts
#### Create an accessibility section referring to the links below
https://yamada-ui.com/components/disclosure/tabs/accessibility#aria-roles-and-attributes ( https://github.com/yamada-ui/yamada-ui/issues/1552 )
https://www.radix-ui.com/primitives/docs/components/accordion#accessibility
https://mantine.dev/core/color-picker/#accessibility

#### Include the following content
* keboard interaction
* aria, tabindex property are supported

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by nakayan5** [comment]
related https://github.com/yamada-ui/yamada-ui/issues/2085

**Comment by nakayan5** [comment]
related https://github.com/yamada-ui/yamada-ui/issues/2084
