### ISSUE TITLE
Add accessibility section for `menu`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#1545]
### Subject

accessibility section for `menu`

#### this issue include file below
- menu-button.tsx
- menu-item.tsx
- menu-list.tsx

#### Create an accessibility section referring to the links below
https://yamada-ui.com/components/disclosure/tabs/accessibility#aria-roles-and-attributes ( https://github.com/yamada-ui/yamada-ui/issues/1552 )
https://www.radix-ui.com/primitives/docs/components/menubar#accessibility
https://v2.chakra-ui.com/docs/components/menu#accessibility
https://mantine.dev/core/menu/#accessibility

#### Include the following content
* keyboard interaction
* aria, role, tabindex property are supported
* link for W3C
  * https://w3.org/WAI/ARIA/apg/patterns/menubar/
  * https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/
  
 #### Reference
https://github.com/yamada-ui/yamada-ui/issues/1923
  
### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by nakayan5** [comment]
related https://github.com/yamada-ui/yamada-ui/issues/1923
