### ISSUE TITLE
Add accessibility section for `pin-input`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#1548]
### Subject

accessibility section for `pin-input`

#### Create an accessibility section referring to the links below
https://yamada-ui.com/components/disclosure/tabs/accessibility#aria-roles-and-attributes ( https://github.com/yamada-ui/yamada-ui/issues/1552 )
https://mantine.dev/core/pin-input/#accessibility

#### Include the following content
* keboard interaction
* aria, tabindex property are supported

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by uraaaa24** [comment]
@hirotomoyamada 
For key interactions, should we support movement with `arrowRight` and `arrowLeft`?
This operation is supported in Mantine and Chakra UI, but not in Yamada UI.

**Comment by hirotomoyamada** [comment]
@uraaaa24 

I would like to support keyboard operation in Yamada UI as well!
