### ISSUE TITLE
Add accessibility section for `radio`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#1549]
### Subject

accessibility section for `radio`

#### Create an accessibility section using the link below
https://yamada-ui.com/components/disclosure/tabs/accessibility#aria-roles-and-attributes
https://www.radix-ui.com/primitives/docs/components/radio-group#accessibility
https://mantine.dev/core/radio/#accessibility
https://mui.com/material-ui/react-radio-button/#accessibility

#### Include the following content
* keboard interaction
* aria, tabindex property are suported
* link for W3C(https://www.w3.org/WAI/ARIA/apg/patterns/radio/)

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by Haru-0001** [comment]
I will try this issue.
