### ISSUE TITLE
Fix class name in `Notice`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#1588]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Corrected the following class names according to BEM

- `ui-notice__list__item`
  - fix to `ui-notice__item`
- `ui-notice__list__item__inner`
  - `ui-notice__item-inner`

Create the changeset with `major`.
Please derive a new branch from the `v2.0` branch and create a pull request for the `v2.0` branch, not the `main` branch, as we plan to release the product in v2.0.0.

Fix the test code if necessary.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by cidkumagai** [comment]
Hi @illionillion, can I work on this one?

**Comment by illionillion** [comment]
> Hi @illionillion, can I work on this one?

Hi @cidkumagai !
Sure, I will assign you.
Good luck!

**Comment by illionillion** [comment]
This issue was closed.
