### ISSUE TITLE
Fix class name in `Select`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#1598]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Corrected the following class names according to BEM

- `ui-select__item__group-label`
  - fix to `ui-select__group-label`
- `ui-select__item__group`
  - fix to `ui-select__group`
- `ui-select__item__icon`
  - `ui-select__item-icon`

Create the changeset with `major`.
Please derive a new branch from the `v2.0` branch and create a pull request for the `v2.0` branch, not the `main` branch, as we plan to release the product in v2.0.0.

Fix the test code if necessary.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by okuyama-code** [comment]
こんにちは、@illionillionさん。こちらのissueの修正に取り組んでもよろしいでしょうか？

**Comment by hirotomoyamada** [comment]
@illionillion 

Hi, thanks for the comment!

Yes, pls.

**Comment by illionillion** [comment]
This issue was closed.
