### ISSUE TITLE
Bug in `allowCreate` in `Autocomplete`

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#1622]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.10

### Description

If you put in `items` containing groups, when you create an element, the original list is also changed.

```tsx
{
  const items: AutocompleteItem[] = [
    { label: "ベジータ", value: "ベジータ" },
    {
      label: "地球人",
      items: [
        { label: "孫悟空", value: "孫悟空" },
        { label: "孫悟飯", value: "孫悟飯" },
        { label: "クリリン", value: "クリリン" },
      ],
    },
    {
      label: "フリーザ軍",
      items: [
        { label: "フリーザ", value: "フリーザ" },
        { label: "ギニュー", value: "ギニュー" },
        { label: "リクーム", value: "リクーム" },
        { label: "バータ", value: "バータ" },
        { label: "ジース", value: "ジース" },
        { label: "グルド", value: "グルド" },
      ],
    },
  ]

  return (
    <>
      <Text>allow create</Text>
      <Autocomplete
        items={items}
        allowCreate
        insertPositionItem={["地球人", "first"]}
      />
      <Text>disallow create</Text>
      <Autocomplete items={items} />
    </>
  )
}
```
https://github.com/yamada-ui/yamada-ui/assets/9676316/7efaefe0-e868-4a4a-b35f-6f208ebaa11e

### Steps to Reproduce

1. Define two `Autocomplete` and `items` containing groups.
2. Pass its `items` to both `Autocomplete`.
3. Set `Autocomplete` on one side to `allowCreate` and create the element.
4. You can see that it has been added to the other `Autocomplete` element.

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by 108yen** [comment]
`use-autocomplete.tsx`
```diff:tsx
  const onCreate = useCallback(() => {
    if (!listRef.current) return

    const newItem: AutocompleteItem = { label: inputValue, value: inputValue }

    let newItems: AutocompleteItem[] = []

-     if (resolvedItems) newItems = resolvedItems
+    if (resolvedItems) newItems = JSON.parse(JSON.stringify(resolvedItems))
```

**Comment by hirotomoyamada** [comment]
@108yen 

You can not use `useMemo` inside `useCallback`.

Approach it like this.

```diff
const [resolvedItems, setResolvedItems] = useState<
  AutocompleteItem[] | undefined
- >(items)
+ >(items ? JSON.parse(JSON.stringify(items)) : undefined)
```
