### ISSUE TITLE
Remove `cleanup` in `range-slider` test code

### ISSUE THREAD

**Issue by teru12012000** [yamada-ui/yamada-ui#1648]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.11

### Description

There is a `cleanup` in the `range-slider` test code. We think that `cleanup` should be removed since it is now in the library.

#1647

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

I think I would resolve the following.

 ```diff
test("can change RangeSlider orientation", () => {
-  const { container } = render(
+  const { container, rerender } = render(
```

```diff
    expect(filledTrack).toHaveStyle("height: 100%")

-   cleanup()

-   const { container: horizontalContainer } = render(
-     <RangeSlider orientation="horizontal" data-testid="slider" />,
-   )
+  rerender(<RangeSlider orientation="horizontal" data-testid="slider" />)

-  sliderThumbs = horizontalContainer.querySelectorAll(".ui-slider__thumb")
-  filledTrack = horizontalContainer.querySelector(".ui-slider__track")
+  sliderThumbs = container.querySelectorAll(".ui-slider__thumb")
+  filledTrack = container.querySelector(".ui-slider__track")

```

**Please provide any additional information.**

**Comment by toshi119** [comment]
お久しぶりです。先週ボードゲームの交流会でお会いした、としです！
てるし〜さんからお誘いがあり、このissue僕がやりたいです
