### ISSUE TITLE
Remove `cleanup` in `toggle-group` test code

### ISSUE THREAD

**Issue by teru12012000** [yamada-ui/yamada-ui#1649]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.11

### Description

There is a cleanup in the `toggle-group` test code. We think that cleanup should be removed since it is now in the library.

#1647

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

I think I would resolve the following.

```diff
describe("<ToggleGroup />", () => {

- afterEach(() => {
-   cleanup()
- })

   test("should render ToggleGroup and its children correctly", async () => {
```
**Please provide any additional information.**

**Comment by sacky3105** [comment]
I would like to challenge this issue.

**Comment by hirotomoyamada** [comment]
@sacky3105 

Thanks for the comment!

Yes, pls.
