### ISSUE TITLE
Modify anchor link position

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1675]
### Provide the exact quote of the error or issue

Currently the anchor link is placed to the left of the heading and is covered by the scroll bar. 
It would be better to place it to the right of the heading.

![スクリーンショット 2024-05-28 21 29 47](https://github.com/yamada-ui/yamada-ui/assets/63556889/e27917da-ca47-4f32-8734-e2e562e85db1)

### Does the docs page already exist? Please link to it.

all pages

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by shivamksharma** [comment]
Fixing It : #1675

**Comment by hirotomoyamada** [comment]
@shivamksharma 

Hi, thanks for the comment!

Already fixed in #1679 :)
