### ISSUE TITLE
The type definition of `onLoad` in `useInfiniteScroll` is wrong

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#1698]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.12

### Description

Currently, the only return value of `onLoad` is `Promise`, but `void` should also be allowed.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

```diff
/**
 * The callback invoked when trigger is intersect.
 */
onLoad?: ({
  index,
  entry,
  finish,
}: {
  index: number
  finish: () => void
  entry?: IntersectionObserverEntry
- }) => Promise<void>
+ }) => void | Promise<void>
```

**Comment by seobbang** [comment]
Hi @hirotomoyamada, can I work on this one?

**Comment by hirotomoyamada** [comment]
@seobbang 

Hi, thanks for the comment!

Yes, pls.

I'll assign this issue to you.
