### ISSUE TITLE
Fix `toHaveClass` in `Rating` component test

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#1955]
### Description

The tests in `Rating` currently test if it has the class `css-14gxg28` (line 48) and `css-sqp1dq` (line 59).

### Problem Statement/Justification

These are randomly generated, and the test will fail if css changes.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by ayanami77** [comment]
I will work on this issue.

**Comment by hirotomoyamada** [comment]
packages/components/rating/tests/rating.test.tsx
