### ISSUE TITLE
Enhance the accessibility of `InfiniteScrollArea` (@yamada-ui/infinite-scroll-area) component

### ISSUE THREAD

**Issue by koralle** [yamada-ui/yamada-ui#1961]
### 1. Accessibility roles

![infinite-scroll-area](https://github.com/yamada-ui/yamada-ui/assets/33865215/5cf4d540-40e1-4bbf-8649-5636e9fa583b)

### 2. `aria-busy`

* [ ] When article elements are being added to or removed from the feed container, and if the operation requires multiple DOM operations, the `feed` element has `aria-busy` set to `true` during the update operation. Note that it is extremely important that `aria-busy` is set to `false` when the operation is complete or the changes may not become visible to some assistive technology users.

### 3. `aria-posinset`

* [ ] Each article element has [aria-posinset](https://w3c.github.io/aria/#aria-posinset) set to a value that represents its position in the feed.

### 4. `aria-setsize`

* [ ] Set `aria-setsize="-1"` for each `<article>` element within the elements that have the `feed` role."

### Keyboard Interaction

* [ ] `Page Down`: Move focus to next article.
* [ ] `Page Up`: Move focus to previous article.
* [ ] `Control + End`: Move focus to the first focusable element after the feed.
* [ ] `Control + Home`: Move focus to the first focusable element before the feed.

### References

* [Infinite Scrolling Feed Example | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/feed/examples/feed/)
* [InfiniteScrollArea - Yamada UI](https://yamada-ui.com/components/data-display/infinite-scroll-area)
* [Feed Pattern | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/feed/)
* [Element: ariaSetSize プロパティ - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/Element/ariaSetSize)

### Problem Statement/Justification

We should prioritize web accessibility to ensure our UI components are usable by everyone, including people with disabilities. This inclusivity enhances user experience and complies with legal standards, broadening Yamada UI's user base.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by nakayan5** [comment]
related https://github.com/yamada-ui/yamada-ui/issues/1496
