### ISSUE TITLE
Replace the documentation site icon with `@yamada-ui/lucide`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2042]
### Subject

All pages

### Description

Currently, We are using the icon from `@yamada-ui/fontawesome`, but I would like to replace it with the icon from `@yamada-ui/lucide`.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by Hayato1031** [comment]
I`ll try this issue.
