### ISSUE TITLE
Replace the example pages icon with `@yamada-ui/lucide`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2043]
### Subject

examples

### Description

Currently, We are using the icon from `components/media-and-icons` and `@yamada-ui/fontawesome`, but I would like to replace it with the icon from `@yamada-ui/lucide`.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by zonoryo17** [comment]
I will work on this issue.
