### ISSUE TITLE
`AccordionItem` background color is not applied.

### ISSUE THREAD

**Issue by Haru-0001** [yamada-ui/yamada-ui#2057]
### Provide the exact quote of the error or issue

Accordion background color is not applied in the document.

### `Accordion`  running on documentation
![image](https://github.com/yamada-ui/yamada-ui/assets/166319111/8c9d5a9e-349a-4363-926c-2ad9e779e9da)

### `Accordion`  running on Storybook
![image](https://github.com/yamada-ui/yamada-ui/assets/166319111/83557b6c-f264-44a1-9c7e-1539fab525ac)

### Browser
Chrome

### Operating System
Windows

This bug may be caused by the browser or the operating system.
I apologize if my perception is incorrect.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/ja/components/disclosure/accordion#accordionlabel%E3%82%92%E4%BD%BF%E3%81%86

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@Haru-0001 @cidkumagai @koralle 

This #2026 caused _expanded not to work.

**Comment by cidkumagai** [comment]
I'll try it.
