### ISSUE TITLE
What is stated on the `Tabs` accessibility page is probably incorrect.

### ISSUE THREAD

**Issue by Haru-0001** [yamada-ui/yamada-ui#2106]
### Provide the exact quote of the error or issue

Wouldn't "next tab" be more appropriate for `ArrowRight` and "previous tab" for `ArrowLeft`?
![image](https://github.com/yamada-ui/yamada-ui/assets/166319111/884c7da9-1589-4714-99fa-c467e4eb2f2a)

 `ArrowRight`で次のタブ、`ArrowLeft` で前のタブといった表現の方が適切ではないでしょうか？

![image](https://github.com/yamada-ui/yamada-ui/assets/166319111/1349feb5-70c8-4bdc-a3c4-789d509fbb0d)

I apologize if my point is incorrect.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/disclosure/tabs/accessibility#keyboard-navigation

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

**Comment by hirotomoyamada** [comment]
@Haru-0001 

Hi, thanks for the issue.

Yes, your opinion is correct. I also think this is the opposite.

**Comment by Haru-0001** [comment]
> @Haru-0001
> 
> Hi, thanks for the issue.
> 
> Yes, your opinion is correct. I also think this is the opposite.

Thanks for your prompt reply.  I will try this issue.
