### ISSUE TITLE
SelectのdefaultValueが無視されてしまう

### ISSUE THREAD

**Issue by mingos** [yamada-ui/yamada-ui#2179]
### どのパッケージに問題がありますか？

@yamada-ui/react

### パッケージのバージョン

1.4.2

### 概要

ドキュメントのSelectの初期値を設定するコードをそのまま貼り付けると、選択状態は正しいものの、
UIの見た目に初期値が反映されていません。

```js
<Select placeholder="キャラクターを選択" defaultValue="ベジータ">
  <Option value="孫悟空">孫悟空</Option>
  <Option value="ベジータ">ベジータ</Option>
  <Option value="フリーザ">フリーザ</Option>
</Select>
```

![image](https://github.com/yamada-ui/yamada-ui/assets/19461/07b95c9c-0b52-4749-877e-a21ca2d46098)
![image](https://github.com/yamada-ui/yamada-ui/assets/19461/00331588-3cd5-4709-b7da-762afbc28677)

### 再現へのリンク

https://codesandbox.io/p/sandbox/yamada-ui-react-cql27v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxvkh9dw0006336mhf8bkd5n%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxvkh9dv0002336mh2wfj5cp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxvkh9dv0003336mnh4ig2ml%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxvkh9dv0005336mui0habzm%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxvkh9dv0002336mh2wfj5cp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvkh9dv0001336majwpuiqs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clxvkh9dv0002336mh2wfj5cp%2522%252C%2522activeTabId%2522%253A%2522clxvkh9dv0001336majwpuiqs%2522%257D%252C%2522clxvkh9dv0005336mui0habzm%2522%253A%257B%2522id%2522%253A%2522clxvkh9dv0005336mui0habzm%2522%252C%2522activeTabId%2522%253A%2522clxvkj4mb000y336mk3ber39i%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvkh9dv0004336mh1iu4hom%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clxvkj4mb000y336mk3ber39i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxvkh9dv0003336mnh4ig2ml%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxvkh9dv0003336mnh4ig2ml%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 再現手順

1. Sandboxをブラウザで開くか、ドキュメントのSelectのdefaultValueの説明のコードを貼り付けます。
2.  defaultValueで指定している「ベジータ」が表示されているはずが、placeholderが表示されています。
3.  Selectをクリックすると、内部の選択状態ではdefaultValueが反映されているようです。

### ブラウザ

Chrome

### OS

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### まさか、問題の修正方法をご存知ですか？

いいえ

### この問題の修正に参加し、修正を含むプルリクエストを作成しますか？

いいえ

**Comment by hirotomoyamada** [comment]
@mingos 

こんにちは、報告ありがとうございます。

この不具合は、Sandboxだけですか？他の環境でも同様の現象が発生しますか？

ドキュメントサイトやStorybookを確認しましたが、再現しませんでした。

**Comment by mingos** [comment]
@hirotomoyamada 

こんにちは。私のローカル環境(vagrant+VirtualBox + Rocky Linux)でも100%再現します。
npm create vite@latestで、React, TypeScript, SWCで作ったプロジェクトです。
sandboxでも再現しているので組み合わせは関係ないのかもしれません。

**Comment by hirotomoyamada** [comment]
@mingos 

ありがとうございます。

macOSでもvite, React, TypeScript, SWCで再現できました。

不具合を調査していきます。

**Comment by mingos** [comment]
@hirotomoyamada 
ご確認ありがとうございます。
よろしくお願い致します。

**Comment by hirotomoyamada** [comment]
@mingos 

`Autocomplete`でも同様な不具合が発生しています。

この不具合は、ReactのStrictModeが原因のようです。余分にエフェクトが実行されるため、正しく値を参照できていないようです。

修正を待ちの間の解決策は、ReactのStrictModeを無効にすることです。

**Comment by hirotomoyamada** [comment]
この不具合を解決するには、

### `packages/components/select/src/use-select.ts`

```diff
const onChangeLabel = useCallback(
  (newValue: string, runOmit: boolean = true) => {
    const values = descendants.values()

+    if (!values.length) return

    const selectedValues = values
      .filter(({ node }) => node.dataset.value === newValue)
      .map(({ node, index }) => {
        if (!(!!placeholder && placeholderInOptions) || index !== 0) {
          const el = Array.from(node.children).find(
            (child) => child.getAttribute("data-label") !== null,
          )

          return el?.innerHTML ?? ""
        } else {
          return undefined
        }
      })

    setLabel((prev) => {
      if (!isMulti) {
        return selectedValues[0] as T
      } else {
        selectedValues.forEach((selectedValue) => {
          const isSelected =
            isArray(prev) && prev.includes(selectedValue ?? "")

          if (!isSelected) {
            prev = [...(isArray(prev) ? prev : []), selectedValue] as T
          } else if (runOmit) {
            prev = (
              isArray(prev)
                ? prev.filter((value) => value !== selectedValue)
                : undefined
            ) as T
          }
        })

        return prev
      }
    })
  },
  [descendants, isMulti, placeholder, placeholderInOptions],
)
```

### `packages/components/autocomplete/src/use-autocomplete.tsx`

```tsx
const onChangeLabel = useCallback(
  (newValue: string, runOmit: boolean = true) => {
    const selectedValues = getSelectedValues(newValue)

+    if (!selectedValues.length) return

    setLabel((prev) => {
      if (!isMulti) {
        return selectedValues[0] as T
      } else {
        selectedValues.forEach((selectedValue) => {
          const isSelected =
            isArray(prev) && prev.includes(selectedValue ?? "")

          if (!isSelected) {
            prev = [...(isArray(prev) ? prev : []), selectedValue] as T
          } else if (runOmit) {
            prev = (
              isArray(prev)
                ? prev.filter((value) => value !== selectedValue)
                : undefined
            ) as T
          }
        })

        return prev
      }
    })
  },
  [getSelectedValues, isMulti],
)
```

選択された配列の値が空だった場合、処理を中止することです。

**Comment by mingos** [comment]
@hirotomoyamada 

確かにnpm run buildでproduction用に生成された状態を確認したところ、不具合が起きていない事が確認出来ました。
開発中はStrictModeを使用したほうが望ましいと思いますので修正を待ちます。
取り急ぎの解決策についても教えて頂きありがとうございました。

**Comment by hirotomoyamada** [comment]
@Shunii85 

I would like to resolve this issue ASAP, can I get a PR?

**Comment by Shunii85** [comment]
@hirotomoyamada 
I'm sorry! I've been trying to understand this content.

I will make a PR.

**Comment by Shunii85** [comment]
@hirotomoyamada 

When I run changeset command, is it true to select 'patch'?

**Comment by hirotomoyamada** [comment]
@Shunii85 

Yes, that is correct.

**Comment by Shunii85** [comment]
I'm trying to find the cause of test error...
