### ISSUE TITLE
Thematize `Image` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2209]
### Description

Yamada UI components are tied to a theme. However, the `Image` component does not have a theme.### 

### Problem Statement/Justification

Themes have `defaultProps`, which can be utilized to share `props` throughout the project. However, the `Image` component does not have a theme, so it cannot take advantage of them.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by cidkumagai** [comment]
I'll try it.
