### ISSUE TITLE
Make `start` and `end` the default

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2215]
### Description

Currently, Yamada UI components default to `left` and `right`. Replace them with `start` and `end`. Also, fix `props` that do not support `start` and `end`.

### Problem Statement/Justification

Expressions such as `left` and `right` change their meaning when the element is rotated.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by hirotomoyamada** [comment]
Working branches are created from `v2.0`.

**Comment by mokun632** [comment]
i'll try it.
