### ISSUE TITLE
`AccordionLabel` does not match the theme key.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2217]
### Description

Currently, the key of the theme is `button`. Since it is also a `button` in role, rename `AccordionLabel` to `AccordionButton`.

### Problem Statement/Justification

It is wrong if the names do not match or are not appropriate for the role.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

If you rename it to `AccordionButton`, you will need to change the name of the `props`, the description of the `JSDoc`, and everywhere else.

**Comment by kaitobq** [comment]
Is all I have to do in this issue is rewrite all AccordionLabel to AccordionButton?

**Comment by hirotomoyamada** [comment]
To do,

1. rename the component from `AccordionLabel` to `AccordionButton`.
2. Change the `label` in `props` to `button`.
3. Fix `label` in the description of `JSDoc`.
4. change the description of Storybook and documentation site.

**Comment by hirotomoyamada** [comment]
@kaitobq 

Working branches are created from `v2.0`.

**Comment by kaitobq** [comment]
@hirotomoyamada  Thank you. I will try it.

**Comment by hirotomoyamada** [comment]
Fixed #2240
