### ISSUE TITLE
improve `Skeleton` test code

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#2226]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.3

### Description

improve test code

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by mokun632** [comment]
i'll try it.

**Comment by illionillion** [comment]
> i'll try it.

Thanks!
Good ruck!!
