### ISSUE TITLE
fix className to BEM

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#2245]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.4

### Description

- `packages/components/carousel/src/carousel-slide.tsx`
  - `ui-carousel__slide__inner`
- `packages/components/carousel/src/carousel.tsx`
  - `ui-carousel__sliders__inner`
- `packages/components/autocomplete/src/multi-autocomplete.tsx`
  - `ui-multi-autocomplete__field__input`

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
Please create a working branch from `v2.0`.Pull requests should also be made from `v2.0` as a target branch.

**Comment by hirotomoyamada** [comment]
@illionillion 

Please add a little more explanation.

**Comment by hirotomoyamada** [comment]
Fixed.
