### ISSUE TITLE
[Accessibility] Tri-State Checkbox 

### ISSUE THREAD

**Issue by koralle** [yamada-ui/yamada-ui#2260]
### Description

Related #1492 

## Description

I was considering the accessibility of the Checkbox component according to the [ARIA Authoring Practices Guide (APG)](https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/). For the Dual-State Checkbox, the current Checkbox is sufficient to ensure accessibility. On the other hand, I thought it was necessary to create a new component for the Tri-State Checkbox.

![](https://private-user-images.githubusercontent.com/33865215/334108279-6919683d-e8a4-480e-859e-164bc8635a6d.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzAyMzksIm5iZiI6MTcyMDUyOTkzOSwicGF0aCI6Ii8zMzg2NTIxNS8zMzQxMDgyNzktNjkxOTY4M2QtZThhNC00ODBlLTg1OWUtMTY0YmM4NjM1YTZkLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEyNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNjk3OTdjZDc3ZjFmYzE3YjY0YWUzMGE5NmM4ZTYxOGRlNDZlZWFlZGVkMjg0MzFmMDU2NWQ1MjAxNzY1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bBRClKz57DpRPrnnKwkiYLvF6tEsIO8IjNbFnZcHaM)

![](https://private-user-images.githubusercontent.com/33865215/334111239-92061571-ff8e-4686-8ecc-abcea35e3766.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzAyMzksIm5iZiI6MTcyMDUyOTkzOSwicGF0aCI6Ii8zMzg2NTIxNS8zMzQxMTEyMzktOTIwNjE1NzEtZmY4ZS00Njg2LThlY2MtYWJjZWEzNWUzNzY2LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEyNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YjFlYTE5NWE0ODRiOGUzNmNhZGE3OGE5YTRmZWMxZTNjZDM3MDk2NzkwZDJjOGU4NjQ3NjQwNDAwMWJjMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qva-rlikgWPf_AaPHdTxSzkobo9RXx0eXhAaGhf3nWo)

### WAI-ARIA Roles, States, and Properties

* [x] The checkbox has role `checkbox`.
* [ ] The `checkbox` has an accessible label provided by one of the following:
  * [x] Visible text content contained within the element with role `checkbox`.
  * [ ] A visible label referenced by the value of `aria-labelledby` set on the element with role `checkbox`.
  * [ ] `aria-label` set on the element with role `checkbox`.
* [ ] When checked, the checkbox element has state `aria-checked` set to `true`.
* [ ] When not checked, it has state `aria-checked` set to `false`.
* [ ] When partially checked, it has state `aria-checked` set to `mixed`.
* [ ] If a set of checkboxes is presented as a logical group with a visible label, the checkboxes are included in an element with role `group` that has the property `aria-labelledby` set to the ID of the element containing the label.
* [ ] If the presentation includes additional descriptive static text relevant to a checkbox or checkbox `group`, the checkbox or checkbox group has the property `aria-describedby` set to the ID of the element containing the description.

### Problem Statement/Justification

We should prioritize web accessibility to ensure our UI components are usable by everyone, including people with disabilities. This inclusivity enhances user experience and complies with legal standards, broadening Yamada UI's user base.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by hirotomoyamada** [comment]
@koralle 

Hi, is this a feature that already exists?Is this issue closed?
