### ISSUE TITLE
The translate button and coror mode button on the document's `FocusLock` does not work. 

### ISSUE THREAD

**Issue by Haru-0001** [yamada-ui/yamada-ui#2275]
### Package Version

1.4.4

### Description

When I try to select a language by pressing the translate button on the `FocusLock` of the document, the menu disappears.
However, this could not be confirmed on other pages.

PS: The color mode button did not work either.

### Link to Reproduction

https://yamada-ui.com/ja/components/other/focus-lock

### Steps to Reproduce

1. Go to https://yamada-ui.com/ja/components/other/focus-lock
2. Click on Open language switching menu.
3. Move the cursor.
4. Menu disappears

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

No

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

My apologies if this bug is due to my environment.

**Comment by hirotomoyamada** [comment]
@Haru-0001 

This is a specification.If it is ``FocusLock``, anything in the area outside of it will not be focused, so this is the correct behavior.
