### ISSUE TITLE
Fix `v2.0` Unit Tests

### ISSUE THREAD

**Issue by cidkumagai** [yamada-ui/yamada-ui#2283]
### Which package has an issue?

@yamada-ui/react

### Package Version

2.0

### Description

This PR aims to refactor these tests to ensure that the applied CSS styles are correctly validated.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

**Comment by cidkumagai** [comment]
I'll try it.

**Comment by hirotomoyamada** [comment]
Fixed #2284
