### ISSUE TITLE
Correction of `music` in `examples`

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#2285]
### Subject

Fix the popover in the application bar section of music so that only one popover is activated

### Description

Fix the popover in the application bar section of music so that only one popover is activated.

https://github.com/user-attachments/assets/76f509ff-c302-45b5-b71e-31e2ce8146f4

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by mmmmaximus** [comment]
Hi @illionillion I would like to try working on this issue, is there any guidelines on the documentation i should follow?

**Comment by illionillion** [comment]
> Hi @illionillion I would like to try working on this issue, is there any guidelines on the documentation i should follow?

Hi @mmmmaximus , 

Good luck!
