### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/charts`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2353]
package: @yamada-ui/charts

### Description
`@yamada-ui/charts` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/charts/src/chart.types.ts](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/charts/src/chart.types.ts)
  - [L166](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/charts/src/chart.types.ts#L166)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by setodeve** [comment]
@hirotomoyamada 
The target of this test is type.
Should we add a test for this?

**Comment by hirotomoyamada** [comment]
@setodeve @108yen 

There is no need to do this.

The only problem with this is that there is no `ChartLabel` in the source code.

**Comment by 108yen** [comment]
@hirotomoyamada 
`ChartLabel` is used by the user to customize the label.
https://github.com/yamada-ui/yamada-components/pull/445

**Comment by hirotomoyamada** [comment]
@108yen 

Can I use it on the source code? Otherwise, the test won't pass.

**Comment by 108yen** [comment]
@hirotomoyamada 
It's possible, but it doesn't make much sense.
Rather than that, what about adding a test to customize `label`?
