### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/loading`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2355]
package: @yamada-ui/loading

### Description
`@yamada-ui/loading` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/loading/src/loading-provider.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/loading/src/loading-provider.tsx)
  - [L248](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/loading/src/loading-provider.tsx#L248)
  - [L276](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/loading/src/loading-provider.tsx#L276)
  - [L314](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/loading/src/loading-provider.tsx#L314)
  - [L322](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/loading/src/loading-provider.tsx#L322)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by odendayoko** [comment]
This issue has been resolved, so I will close it.
