### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/rating`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2358]
package: @yamada-ui/rating

### Description
`@yamada-ui/rating` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/rating/src/rating-item.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/rating/src/rating-item.tsx)
  - [L34](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/rating/src/rating-item.tsx#L34)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by zonoryo17** [comment]
I'll work on this.

**Comment by hirotomoyamada** [comment]
@zonoryo17 

Hi, thanks for the comment!

Yes, pls!
