### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/switch`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2359]
package: @yamada-ui/switch

### Description
`@yamada-ui/switch` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/switch/src/switch.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/switch/src/switch.tsx)
  - [L93](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/switch/src/switch.tsx#L93)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by haratake22** [comment]
@hirotomoyamada 
I'm new to OSS, but can I try this task?

**Comment by hirotomoyamada** [comment]
@haratake22 

Hi, thanks for the comment!

Yes, of course.

I'll assign this issue to you. Good luck!

**Comment by hirotomoyamada** [comment]
@haratake22

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.

**Comment by kaehehehe** [comment]
Hi, Could you please assign it to me? :)

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, thanks for the comment!

> Hi! Could you please assign it to me? :)

Yes, pls.

**Comment by hirotomoyamada** [comment]
@kaehehehe 

> Also, I have a question: Currently, the icon-related story is not visible in the Switch component. Would it be okay to add it?

This should be proposed by creating a separate issue.
