### ISSUE TITLE
Add `xAxisTickFormatter`, `yAxisTickFormatter` and more to chart components

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2396]
### Subject

AreaChart

### Description

New `props` for `AreaChart` component and others. Document them.

```
- Added `xAxisTickFormatter` and `yAxisTickFormatter` to `AreaChart`, `LineChart`, and `BarChart`.
- Added `labelFormatter` to `AreaChart`, `LineChart`, `BarChart`, and `PieChart`.
- Added `polarAngleAxisTickFormatter` and `polarRadiusAxisTickFormatter` to `RadarChart`.
```

We will work on #2395 when it is merged into `main`.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by 108yen** [comment]
Closed #2413
