### ISSUE TITLE
Add `onDoubleClickRow` Prop to `Table`

### ISSUE THREAD

**Issue by bmthd** [yamada-ui/yamada-ui#2418]
### Description

Add an `onDoubleClickRow` Prop that can receive information when a row in a table component is double-clicked.

### Problem Statement/Justification

Thank you, maintainers, for your wonderful library.
In complex business applications, you may want to assign a different operation when a row is double-clicked.
Currently, if you want to specify a handler for a double click on a row, you need to implement it in NativeTable, which is time-consuming.
Since the React event handler provides onDoubleClick, it seems natural for Yamada UI to provide this feature as well.

### Proposed Solution or API

The following branches were implemented, tested, storied, and documentation updated
If all is well, we would like to create a pull request.
https://github.com/yamada-ui/yamada-ui/compare/main...bmthd:yamada-ui:feat/table-row-dblclick

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

Yes

**Comment by hirotomoyamada** [comment]
Hi, thanks for the issue!

This suggestion is very good!
I would love to implement it!

I looked at the source code for the branch.

It is very good.
However, there are a few things I would like to see fixed.

- docs/contents/components/data-display/table/props.ja.mdx
- docs/contents/components/data-display/table/props.mdx

These files do not need to be modified.
They are generated automatically.

And, there are also differences in the file except for some newly added logic.
This can be tricky to review, so please make sure that only the changes you make cause a difference.
