### ISSUE TITLE
The `Text` component is themed but not present in the default theme.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2440]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.8

### Description

The `Text` component is themed but not present in the default theme.

You should create and export `text.ts` in the `theme/components` folder.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by manasan-iTL** [comment]
@hirotomoyamada 
Can I try this issue?

**Comment by hirotomoyamada** [comment]
@manasan-iTL 

Hi, thanks for the comment!

Yes, pls!
