### ISSUE TITLE
Add description of `theme` in `yamada-ui/cli` to the documentation

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2466]
### Subject

yamada-ui/cli

### Description

Add description of `theme` in `yamada-ui/cli` to the documentation.

#2432 

Reflect the work done in this PR.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by tiluckdave** [comment]
@hirotomoyamada Can I do this?

**Comment by hirotomoyamada** [comment]
@tiluckdave 

Hi, thanks for the comment!

Yes, pls.
