### ISSUE TITLE
Add `minRangeDates` and `maxRangeDates` to `RangeDatePicker`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2467]
### Description

Add `minRangeDates` and `maxRangeDates` to `RangeDatePicker`. This allows you to set minimum and maximum widths for a selection of ranges.

### Problem Statement/Justification

Currently, when you select a range, you cannot set a minimum and maximum.For example, you may want to say that for some projects you can reserve something for up to a week.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by Shunii85** [comment]
Hi @hirotomoyamada !
About `maxRangeDate`, it is already implemented as `maxSelectValues` prop, isn't it ... ? If I am wrong, please tell me the difference.

**Comment by hirotomoyamada** [comment]
@hirotomoyamada 

Hi, thanks for the comment!

The `maxRangeDate` is indeed `maxSelectValues`. I think only `minRangeDates` should be implemented this time.
The name `minSelectValues` might be better to match `maxSelectValues`.
