### ISSUE TITLE
Deprecated props are being used in the Storybook `FontAwesome` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2483]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.8

### Description

Deprecated props are being used in the Storybook `FontAwesome` page.

Use `fontSize` instead of `size`.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by chida09** [comment]
can i work this issue?

maybe I'll fix the section of code below.

https://github.com/yamada-ui/yamada-ui/blob/1473921f8aeb4e2040d0337aee3b101e78884749/stories/components/media-and-icons/font-awesome.stories.tsx#L18-L28

**Comment by hirotomoyamada** [comment]
@chida09 

Hi, thanks for the comment!

Yes, pls!

Those lines are correct.
