### ISSUE TITLE
Deprecated props are being used in the Storybook `Image` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2484]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.8

### Description

Deprecated props are being used in the Storybook `Image` page.

Use `boxSize` instead of `size`.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by dev-satoshi** [comment]
このIssueやりたいです！

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment!

Yes, pls.

I'll assign this issue to you.
