### ISSUE TITLE
Deprecated props are being used in the Storybook `Loading` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2485]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.8

### Description

Deprecated props are being used in the Storybook `Loading` page.

Use `fontSize` instead of `size`.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by tf63** [comment]
@hirotomoyamada 

Hi! Can I do this issue?

**Comment by hirotomoyamada** [comment]
@tf63

Hi, thanks for the comment!

Yes, please.

**Comment by tf63** [comment]
@hirotomoyamada 

I have created a PR. Could you please review it?

- https://github.com/yamada-ui/yamada-ui/pull/2504
