### ISSUE TITLE
Deprecated props are being used in the `Icon` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2486]
### Provide the exact quote of the error or issue

Deprecated props are being used in the `Icon` page.

Use `fontSize` instead of `size`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/media-and-icons/icon

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hro19** [comment]
Hi can I work on this issue?

**Comment by hirotomoyamada** [comment]
@hro19 

Hi, thanks for the comment!

Yes, please.

**Comment by hirotomoyamada** [comment]
Fixed #2538
