### ISSUE TITLE
Deprecated props are being used in the `Image` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2487]
### Provide the exact quote of the error or issue

Deprecated props are being used in the `Image` page.

Use `boxSize` instead of `size`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/media-and-icons/image

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by VarunHarish98** [comment]
Hi, @hirotomoyamada ,
Can you please assign this to me.
I will wokr on this.
Thanks.

**Comment by hirotomoyamada** [comment]
@VarunHarish98 

Hi, thanks for the comment!

Yes, please!

I'll assign this issue to you!
