### ISSUE TITLE
Deprecated props are being used in the `Loading` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2488]
### Provide the exact quote of the error or issue

Deprecated props are being used in the `Loading` page.

Use `fontSize` instead of `size`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/feedback/loading

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by tmasuyama1114** [comment]
Good day! Can I work on this issue?

**Comment by hirotomoyamada** [comment]
@tmasuyama1114 

Hi, thanks very much for your help earlier.

Please do this as well.

**Comment by tmasuyama1114** [comment]
@hirotomoyamada 
I have created PR, so could you please review when you have a time?

- https://github.com/yamada-ui/yamada-ui/pull/2511

thanks!

**Comment by hirotomoyamada** [comment]
@tmasuyama1114 

Amazing! You are working very fast!

Reviews will be done by the maintainer and ultimately reviewed by me.

Please wait for the maintainer's review.

**Comment by tmasuyama1114** [comment]
Sure!

**Comment by hirotomoyamada** [comment]
Fixed #2511
