### ISSUE TITLE
Deprecated props are being used in the `Menu` test code.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2489]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.8

### Description

Deprecated props are being used in the `Menu` test code.

Use `fontSize` instead of `size`.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by tmasuyama1114** [comment]
Good day! Can i work on this issue?
