### ISSUE TITLE
Deprecated props are being used in the `Menu` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2491]
### Provide the exact quote of the error or issue

Deprecated props in the `Lucide` icon used on the `Menu` page.

Use `fontSize` instead of `size`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/overlay/menu

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by ochio** [comment]
Hi! Can I do this?

**Comment by hirotomoyamada** [comment]
@ochio 

Hi, thanks for the comment!

Yes, please!
