### ISSUE TITLE
Deprecated props are being used in the `ContextMenu` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2492]
### Provide the exact quote of the error or issue

Deprecated props in the `Lucide` icon used on the `ContextMenu` page.

Use `fontSize` instead of `size`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/overlay/context-menu

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by Keisuke05410** [comment]
can i work this issue?

**Comment by hirotomoyamada** [comment]
@Keisuke05410 

Hi, thanks for the comment!

Yes, please!

**Comment by hirotomoyamada** [comment]
Fixed #2518
