### ISSUE TITLE
Deprecated props are being used in the `Dropzone` page.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2493]
### Provide the exact quote of the error or issue

Deprecated props in the `Lucide` icon used on the `Dropzone` page.

Use `fontSize` instead of `size`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/forms/dropzone

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by enumura1** [comment]
Hi! can i work on this issue?

**Comment by hirotomoyamada** [comment]
@enumura1 

Hi, thanks for the comment!

Yes, pls!

**Comment by enumura1** [comment]
@hirotomoyamada 
I have submitted a pull request. Please review it.
- https://github.com/yamada-ui/yamada-ui/pull/2500
