### ISSUE TITLE
Deprecated props are being used in the example pages.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2494]
### Provide the exact quote of the error or issue

Deprecated props in the `Lucide` icon used on the example pages.

Use `fontSize` instead of `size`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/examples/mail

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by mk0812** [comment]
can i work this issue?
I'll put the assignment in for me.

**Comment by hirotomoyamada** [comment]
@mk0812 

Hi, thanks for the comment!

Yes, pls!
