### ISSUE TITLE
Deprecated props are being used in the Storybook `InfiniteScrollArea`  page.

### ISSUE THREAD

**Issue by Shunii85** [yamada-ui/yamada-ui#2507]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.8

### Description

Deprecated props are being used in the Storybook `InfiniteScrollArea` page.

Use `fontSize` instead of `size`.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by mk0812** [comment]
can i work this issue??

**Comment by hirotomoyamada** [comment]
@mk0812 

Hi, thanks for the comment!

Yes, pls.

I'll assign this issue to you. Good luck!

**Comment by hirotomoyamada** [comment]
@mk0812 

Hi, Can you please correct the documentation site as well?
