### ISSUE TITLE
Deprecated props are being used in the Storybook `Theme/Loading`page.

### ISSUE THREAD

**Issue by Shunii85** [yamada-ui/yamada-ui#2508]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.8

### Description

Deprecated props are being used in the Storybook `Theme/Loading`page.

Use `fontSize` instead of `size`.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

It's not needed  to fix the Storybook `Components/Feedback/Loading` page.

**Comment by mk0812** [comment]
can i work this issue?

maybe I'll fix the section of code below.
https://github.com/yamada-ui/yamada-ui/blob/1473921f8aeb4e2040d0337aee3b101e78884749/stories/system/theme/loading.stories.tsx#L173

**Comment by hirotomoyamada** [comment]
@mk0812 

Hi, thanks for the comment!

Yes, pls!

That line is correct.
