### ISSUE TITLE
Remove the `size` of the `Image` component in v2

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2512]
### Description

Remove `size` from the `Image` component.

Create the branch you are working on from `v2.0`.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by Tonnykimanthi** [comment]
Hey Hirotomoyamada! I hope you don't mind assigning me the issue. Let me know more about the `Image component` you would like to be fixed

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment!

Yes, pls.

```
/**
 * The CSS `box-size` property.
 *
 * @deprecated Use `boxSize` instead.
 */
size?: CSSUIProps["boxSize"]
```

Please remove this lines.

```diff
- const [styles, { size, ...mergedProps }] = useComponentStyle("Image", props)
+ const [styles, mergedProps] = useComponentStyle("Image", props)
let {
-  boxSize,
  fit: objectFit,
  fallback,
  src,
  srcSet,
  loading,
  ignoreFallback,
  crossOrigin,
  className,
  fallbackStrategy = "beforeLoadOrError",
  onError,
  onLoad,
  referrerPolicy,
  ...rest
} = omitThemeProps(mergedProps)

- boxSize ??= size
ignoreFallback = loading != null || ignoreFallback || !fallback

const css = useMemo(
-  () => ({ ...styles, boxSize, objectFit }),
+ () => ({ ...styles, objectFit }),
  [styles, boxSize, objectFit],
)

```

**Comment by hirotomoyamada** [comment]
@Tonnykimanthi

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.

**Comment by chida09** [comment]
I'll try it.

**Comment by Haru-0001** [comment]
This isuue is closed again due to the existence of similar isuues and PRs #3500 and #3505.
