### ISSUE TITLE
Add documentation of `header` and `footer` for `Select` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2520]
### Subject

Select

### Description

#2519 

Add the functionality added by this PR to the document.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by kaehehehe** [comment]
I have completed the work!

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, thanks for the PR.

Looking at the PR you created, it looks like you're adding to the stories.

However, the content of this issue is to add to the documentation site, i.e. docs.
