### ISSUE TITLE
Add documentation of `header` and `footer` for `Autocomplete` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2522]
### Subject

Autocomplete

### Description

#2519 

Add the functionality added by this PR to the document.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by hirotomoyamada** [comment]
Please refer to #2634.

**Comment by kaehehehe** [comment]
It's similar to https://github.com/yamada-ui/yamada-ui/pull/2634, so I'll take care of it!

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, thanks for the comment!

Yes, pls.
