### ISSUE TITLE
Add documentation of `header` and `footer` for `MultiAutocomplete` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2523]
### Subject

MultiAutocomplete

### Description

#2519 

Add the functionality added by this PR to the document.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by Code-Hacker26** [comment]
@hirotomoyamada I am interested in working on this issue!

**Comment by hirotomoyamada** [comment]
@Code-Hacker26 

Hi, thanks for the comment!

Yes, pls!

**Comment by hirotomoyamada** [comment]
@hinataOhyama 

Hi, thanks for the works.

Please refer to #2634.
