### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/select`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2535]
package: @yamada-ui/select

### Description
`@yamada-ui/select` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/select/src/select-list.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/select/src/select-list.tsx)
  - [L51](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/select/src/select-list.tsx#L51)
  - [L65](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/select/src/select-list.tsx#L65)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by kaehehehe** [comment]
Could you please assign this to me?

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, thanks for the comment!

Yes, pls.

**Comment by kaehehehe** [comment]
I have a question. It seems that the SelectList component doesn't have a story. Is it okay to write a story for it? @hirotomoyamada

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, That page does not need to be added. 

This is because the `SelectList` component is a component used within the `Select` component, not by itself.

https://yamada-ui.github.io/yamada-ui/?path=/story/components-forms-select--basic

**Comment by kaehehehe** [comment]
I see! I understand now! Thank you :)
