### ISSUE TITLE
Remove some props from `UIProps`.

### ISSUE THREAD

**Issue by Shunii85** [yamada-ui/yamada-ui#2563]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.9

### Description

Following props should be removed  from `UIProps` because they overlap with the props in `styleProperties`
- textStyle
- layerStyle
- apply
- lineClamp

https://github.com/yamada-ui/yamada-ui/blob/f451f68a7956dc6b75056e44d344f38b0a601191/packages/core/src/components/should-forward-prop.ts#L4-L17

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@Shunii85 

Hi, thanks for the comment!

There is no `css` in `styleProperties`.
Please correct the issue.
