### ISSUE TITLE
The heading for "Customize icons" on the MultiAutocomplete Japanese page is incorrect

### ISSUE THREAD

**Issue by hironokobari** [yamada-ui/yamada-ui#2619]
### エラーまたは問題の正確な引用

The heading for "Customize icons" on the MultiAutocomplete Japanese page is incorrect.

<img width="343" alt="スクリーンショット 2024-08-20 22 53 35" src="https://github.com/user-attachments/assets/a56252e6-0c82-42b4-abd5-58df3ac5a452">

### ドキュメントのページはすでに存在しますか？リンクを貼ってください。

https://yamada-ui.com/ja/components/forms/multi-autocomplete

### この問題の修正に参加し、修正を含むプルリクエストを作成しますか？

はい

**Comment by hirotomoyamada** [comment]
Related #2600
