### ISSUE TITLE
"Hover me!" is listed where it is not a description of the hover.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2673]
### Provide the exact quote of the error or issue

"Hover me!" is listed where it is not a description of the hover.

The correct phrase is "Look me!".

- https://yamada-ui.com/components/other/motion#usage
- https://yamada-ui.com/styled-system/animation#animation

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/other/motion#usage

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by taiseiiiii** [comment]
Would it be all right if I address this issue?

**Comment by hirotomoyamada** [comment]
@taiseiiiii 

Hi, thanks for the comment!

Yes, pls.
