### ISSUE TITLE
Bug that `node="[object Object]"` is specified when customizing markdown

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#2708]
### Which package has an issue?

@yamada-ui/markdown

### Package Version

1.0.41

### Description

Customizing the markdown as follows will result in the image.

![image](https://github.com/user-attachments/assets/797b2afd-afeb-41f1-8b33-74abe04c292d)

```tsx
const components = {
  h2: (props) => (
    <Heading
      size="2xl"
      bgGradient="linear(to-l, #f37bdf, #59a9e1)"
      bgClip="text"
      isTruncated
      {...props}
    />
  ),
}

return <Markdown components={components}>{README}</Markdown>
```

### Link to Reproduction

https://yamada-ui.com/components/data-display/markdown#using-custom-components

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by illionillion** [comment]
@koralle 
Do you know anything about this?

**Comment by koralle** [comment]
@illionillion 

Thanks for reporting! I'll take a look at it myself.
