### ISSUE TITLE
ドロップゾーンコンポーネントが働いていない

### ISSUE THREAD

**Issue by Hayato1031** [yamada-ui/yamada-ui#2746]
### どのパッケージに問題がありますか？

@yamada-ui/dropzone

### パッケージのバージョン

1.0.42

### 概要

DropZoneコンポーネントにファイルをアップロードしても反応せず、
DropzoneAccept,DropzoneReject,DropzoneIdleの動作が確認できなかった。

Yamada-UIのドキュメントサイトのサンプルにおいても同様。

### 再現手順

1. Yamada-UIのドキュメントのDropzoneのコンポーネントのサンプルに行きます。
2. Dropzoneコンポーネントをクリックします。
3. ファイルをアップロードします。
4. 一切表示などが変わりません。

### ブラウザ

Chrome

### OS

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### まさか、問題の修正方法をご存知ですか？

None

### この問題の修正に参加し、修正を含むプルリクエストを作成しますか？

None

**Comment by illionillion** [comment]
@Hayato1031 イシュー作成ありがとうございます。

https://yamada-ui.com/ja/components/forms/dropzone#状態に応じた表示をする

このページについての動作ですが、バグではなく仕様だと思います。

ファイルをアップロードしても反応しないのは、これはあくまでドロップゾーンという役割をもったコンポーネントだからです。
ファイルの内容を表示などの機能は`onDrop`のプロパティに関数を渡して実行するので使う側が独自に実装するものです。

https://yamada-ui.com/ja/components/forms/dropzone#ドロップされたイベントをハンドルする

> DropzoneAccept,DropzoneReject,DropzoneIdleの動作が確認できなかった。

これについても、反応しないのは`accept`属性に受け付ける拡張子を設定していないからではないですか？
ドキュメントではちゃんと画像ファイルをドラッグ&ドロップした時と、それ以外のファイルをドラッグ&ドロップしたときでDropzoneAccept,DropzoneRejectの動作が確認できます。

**Comment by hirotomoyamada** [comment]
@Hayato1031 @illionillion 

Hi, thanks for the issue and comment!

Perhaps it is the behavior when you click on the `Dropzone` rather than when you drag and drop it?

**Comment by illionillion** [comment]
> @Hayato1031
> 
> Hi, thanks for the issue and comment!
> 
> Perhaps it is the behavior when you click on the `Dropzone` rather than when you drag and drop it?
> 
> @illionillion
> 
> If the above is the case, yes, the status is not displayed.

It certainly doesn't behave the same way when you click as it does when you drop.

**Comment by illionillion** [comment]
@hirotomoyamada 

Do you want to implement click behavior as a new feature?

**Comment by hirotomoyamada** [comment]
@illionillion 

Do you mean that when you click on it, it changes status to make it visually clearer?

**Comment by illionillion** [comment]
> @illionillion
> 
> Do you mean that when you click on it, it changes status to make it visually clearer?

@hirotomoyamada 

I thought that when a file was selected and uploaded with a click, it would indicate that the file was in the correct format, but I didn't think it was necessary because files that don't belong to the `accept` category cannot be selected in the first place when clicked.

**Comment by hirotomoyamada** [comment]
@illionillion 

Yes, I agree with that.

However, you might be able to select it depending on the OS, browser, and version.

I think it is worth investigating.

**Comment by illionillion** [comment]
> @illionillion
> 
> Yes, I agree with that.
> 
> However, maybe some OS, browsers, or versions might be able to select it.
> 
> I think it is worth investigating.

@hirotomoyamada 

Major OS and browsers seem to support the `accept` attribute.

https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/accept#%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%83%BC%E3%81%AE%E4%BA%92%E6%8F%9B%E6%80%A7

**Comment by hirotomoyamada** [comment]
@illionillion 

> The accept attribute doesn't validate the types of the selected files; it provides hints for browsers to guide users towards selecting the correct file types. It is still possible (in most cases) for users to toggle an option in the file chooser that makes it possible to override this and select any file they wish, and then choose incorrect file types.
> 
> Because of this, you should make sure that expected requirement is validated server-side.

> When set on a file input type, the native file picker that opens up should only enable selecting files of the correct file type. Most operating systems lighten the files that don't match the criteria and aren't selectable.

I am curious about the above statement.

**Comment by hirotomoyamada** [comment]
@Hayato1031 @illionillion 

Since there is no new discussion, this issue is closed for now. If there is any further discussion, please comment here.
