### ISSUE TITLE
Couldn't see the focus animation

### ISSUE THREAD

**Issue by Shunii85** [yamada-ui/yamada-ui#2755]
### Provide the exact quote of the error or issue

Currently,  it is set in the `focus` event section of the documentation that the `as` prop of the Motion component is `button`. 
However, we are enable to see the animation. So, we should use `input`.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/other/motion#focus

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@Shunii85 

Hi, thanks for the issue.

It seems to be working fine in my environment. Could you please show me a video or something?

**Comment by Shunii85** [comment]
@hirotomoyamada Hi!
I might be wrong on how to properly check the `focus` animation. 
Before taking a video, please advice me!

**Comment by hirotomoyamada** [comment]
@Shunii85 

Hi, just focus the button.The button gets bigger as you focus it.

**Comment by Shunii85** [comment]
@hirotomoyamada 
https://github.com/user-attachments/assets/857aee5e-1002-4b8b-8abb-c7c3ff21091d

**Comment by hirotomoyamada** [comment]
@Shunii85 

Hi, thanks for the movies.

There is a difference between hover and focus. 

There is probably no problem, so close this issue when you are sure that the element is now large enough to focus.

**Comment by Shunii85** [comment]
@hirotomoyamada 
Thanks for the comment!
I could see the animation by enter `tab` key. I'm sorry!
