### ISSUE TITLE
The order of `theming` and `props` is reversed.

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#2772]
### Provide the exact quote of the error or issue

Reverse order of `theming` and `props` in `Button` component documentation

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/forms/button

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
- `docs/contents/components/forms/button/props.mdx`
- `docs/contents/components/forms/button/props.ja.mdx`

It appears that `order: 1` is missing from the front matter of the above path.
