### ISSUE TITLE
Add 2xl breakpoint to useBreakpointValue example

### ISSUE THREAD

**Issue by odendayoko** [yamada-ui/yamada-ui#2775]
### Provide the exact quote of the error or issue

Our current documentation for useBreakpointValue doesn't include an example for the 2xl breakpoint. The existing example is:
```
const bg = useBreakpointValue({
  base: "red.500",
  xl: "blue.500",
  lg: "green.500",
  md: "yellow.500",
  sm: "purple.500",
})
```

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/styled-system/responsive-styles#using-usebreakpoint

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@odendayoko 

Hi, thanks for the issue.

The display shows `2xl`, but it is unfriendly because it does not change color.
