### ISSUE TITLE
Fix incomplete sentence in @media documentation

### ISSUE THREAD

**Issue by odendayoko** [yamada-ui/yamada-ui#2776]
### Provide the exact quote of the error or issue

In the documentation explaining the usage of `@media` , there is an incomplete sentence. 

English:
```
For example, to change the styles displayed in print preview mode using the print media type of @media,
```
Japanese:
```
例えば、@mediaのメディア種別のprintを使い、印刷プレビューモードで表示されるスタイルを変更する場合は、
```

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/styled-system/at-rules#media

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@odendayoko 

Hi, thanks for the issue.

How do you think the above sentence should be modified?

**Comment by odendayoko** [comment]
@hirotomoyamada 
Sorry!!
I would like you to complete the sentence.

English:
```
For example, here is an example of using @media's media type print to change the style displayed in print preview mode.
```
Japanese:
```
例えば、@mediaのメディア種別のprintを使い、印刷プレビューモードで表示されるスタイルを変更する場合の例です。
```
