### ISSUE TITLE
The description of ColorSwatch in the ja is incorrect

### ISSUE THREAD

**Issue by hiogramming** [yamada-ui/yamada-ui#2801]
### Provide the exact quote of the error or issue

The description of ColorSwatch in the ja is incorrect.
It says ColorPicker instead.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/ja/components/data-display/color-swatch

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

**Comment by hirotomoyamada** [comment]
@hiogramming 

Hi, thanks for the issue.

Please correct it!
