### ISSUE TITLE
Correct Loading's size to fontSize.

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#2844]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.2

### Description

Deprecated size is used, fix it

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by bearone236** [comment]
I'll try this issue.

**Comment by illionillion** [comment]
![image](https://github.com/user-attachments/assets/9ec5705b-d41a-4eeb-bf06-54b66fe255a1)
