### ISSUE TITLE
`displayName` is not set for the component of "@yamada-ui/image"

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2871]
script: component-display-name
package: @yamada-ui/image

### Description
The component "@yamada-ui/image" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

**Comment by sonitan0803** [comment]
hello
I want to challenge
(Since this is my first time participating in OSS, I will start work after checking the rules)

**Comment by hirotomoyamada** [comment]
@sonitan0803 

Hi, thanks for the comment!

Yes, pls!
