### ISSUE TITLE
`displayName` is not set for the component of "@yamada-ui/loading"

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2879]
script: component-display-name
package: @yamada-ui/loading

### Description
The component "@yamada-ui/loading" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

**Comment by toshi119** [comment]
I try it.

**Comment by hirotomoyamada** [comment]
@toshi119 

Thanks for the comment!

Yes, pls!

**Comment by hirotomoyamada** [comment]
@toshi119

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.
