### ISSUE TITLE
`displayName` is not set for the component of "@yamada-ui/notice"

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2887]
script: component-display-name
package: @yamada-ui/notice

### Description
The component "@yamada-ui/notice" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

**Comment by Kei-Ta** [comment]
@hirotomoyamada 
Can I try it?

**Comment by hirotomoyamada** [comment]
@Kei-Ta 

Hi, yes, pls!

**Comment by hirotomoyamada** [comment]
@Kei-Ta

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.
