### ISSUE TITLE
`displayName` is not set for the component of "@yamada-ui/portal"

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2892]
script: component-display-name
package: @yamada-ui/portal

### Description
The component "@yamada-ui/portal" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

**Comment by taku10101** [comment]
I will try it!!

**Comment by illionillion** [comment]
> I will try it!!

I asigned you.
Good Luck!!

**Comment by taku10101** [comment]
@hirotomoyamada 
portal component is not use `forwardRef`
It`s need to this code?
``` diff 
+ Portal.__ui__ = "ui.portal"
```

**Comment by illionillion** [comment]
> @hirotomoyamada portal component is not use `forwardRef` It`s need to this code?
> 
> ```diff
> + Portal.__ui__ = "ui.portal"
> ```

@taku10101 
Refer this.
https://github.com/yamada-ui/yamada-ui/pull/2940#pullrequestreview-2324817876
