### ISSUE TITLE
`displayName` is not set for the component of "@yamada-ui/tag"

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2910]
script: component-display-name
package: @yamada-ui/tag

### Description
The component "@yamada-ui/tag" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

**Comment by 273Do** [comment]
Hello! This is my first time contributing to an open source project and I'm nervous about it. Is this challenge up to me?

**Comment by hirotomoyamada** [comment]
@273Do 

Hi, thanks for the comment!

Yes, pls!
