### ISSUE TITLE
`displayName` is not set for the component of "@yamada-ui/toggle"

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#2912]
script: component-display-name
package: @yamada-ui/toggle

### Description
The component "@yamada-ui/toggle" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

**Comment by ogane0112** [comment]
As this is my first time contributing to an open-source project, would it be alright if I took on this challenge?
