### ISSUE TITLE
Calendar Component: Arrow icons bug in Chrome and Safari

### ISSUE THREAD

**Issue by chida09** [yamada-ui/yamada-ui#2951]
### Which package has an issue?

@yamada-ui/calendar

### Package Version

1.8.0

### Description

Description:
A bug has been identified in the Calendar component's navigation arrow icons, affecting both Chrome and Safari browsers:

1. In Chrome:
   - Bug: The arrow icons are rendered significantly larger than intended.

<img width="336" alt="スクリーンショット 2024-09-24 22 51 47" src="https://github.com/user-attachments/assets/f2a4dd82-d440-43c4-9865-e692b429c6be">

2. In Safari:
   - Bug: The arrow icons are completely missing (not visible at all).

![スクリーンショット 2024-09-24 22 51 58](https://github.com/user-attachments/assets/dc8da5dc-3824-4d36-a376-3da60e695454)

Expected behavior:
The navigation arrow icons should be visible and correctly sized on both sides of the month/year display across all browsers, as demonstrated in the attached reference image.

<img width="336" alt="スクリーンショット 2024-09-24 22 52 39" src="https://github.com/user-attachments/assets/4cff2da9-a9a7-40ad-830a-cc29dc18f9e6">

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by 108yen** [comment]
PR that caused.
https://github.com/yamada-ui/yamada-ui/pull/2930
