### ISSUE TITLE
Accessibility tab of `Modal` component ja page is written in english

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#3082]
### Provide the exact quote of the error or issue

Accessibility tab of `Modal` component ja page is written in english.
`ARIA Roles and Attributes` and table columns should be japanese.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/ja/components/overlay/modal/accessibility

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by kaehehehe** [comment]
Is this issue resolved? It looks like it's in Japanese. @108yen

**Comment by 108yen** [comment]
@kaehehehe 
No.
Take a closer look.
