### ISSUE TITLE
Wrong text of `InfiniteScrollArea` documentation

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#3152]
### Provide the exact quote of the error or issue

`InfiniteScrollArea inherits the style from .`
`InfiniteScrollAreaは、のスタイルを継承しています。`

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/data-display/infinite-scroll-area/theming

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@108yen 

The same event occurs for all components that do not inherit.

**Comment by 108yen** [comment]
It is needed to fix.
https://github.com/yamada-ui/yamada-ui/blob/d64f0feddd82ff97d2e44232d7e5185df37c4bc9/docs/scripts/component/theme.ts#L37-L98
