### ISSUE TITLE
Use the named export instead of the default export at the Customize Theme Page

### ISSUE THREAD

**Issue by odendayoko** [yamada-ui/yamada-ui#3165]
### Provide the exact quote of the error or issue

Use the named export where it uses the default export at the Customize Theme Page. For example...
from: 
```ts title=./theme/index.ts
import { extendTheme, UsageTheme } from "@yamada-ui/react"
// import styles from './styles'
// import components from './components'
// import tokens from './tokens'

const customTheme: UsageTheme = {
  // styles,
  // components,
  // ...tokens,
}

export default extendTheme(customTheme)()
```
to: 
```ts title=./theme/index.ts
import { extendTheme, UsageTheme } from "@yamada-ui/react"

export const customTheme: UsageTheme = {
  // styles,
  // components,
  // ...tokens,
}

export const theme = extendTheme(customTheme)()
```

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/styled-system/theming/customize-theme

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@odendayoko 

Have you investigated other documentation for similar statements?

**Comment by odendayoko** [comment]
@hirotomoyamada 
Sorry...
The following other examples use defaule export and should be corrected.
### 1. `./theme/tokens/index.ts`

from:
```typescript
import { colors } from "./colors"

export default { colors }
```

to:
```typescript
import { colors } from "./colors"

export const tokens = { colors }
```
### 2. `./theme/styles/index.ts`
from
```ts
import { globalStyle } from "./global-style"

export default { globalStyle }
```
to
```ts
import { globalStyle } from "./global-style"

export const tokens = { globalStyle }
```
### 3. `./theme/components/index.ts`
from:
```ts
import { Container } from "./container"

export default { Container }
```
to:
```ts
import { Container } from "./container"

export const components = { Container }
```

**Comment by hirotomoyamada** [comment]
@odendayoko 

Thx.

**Comment by Shunii85** [comment]
> @hirotomoyamada Sorry... The following other examples use defaule export and should be corrected.
> ### 1. `./theme/tokens/index.ts`
> 
> from:
> 
> ```ts
> import { colors } from "./colors"
> 
> export default { colors }
> ```
> 
> to:
> 
> ```ts
> import { colors } from "./colors"
> 
> export const tokens = { colors }
> ```
> 
> ### 2. `./theme/styles/index.ts`
> 
> from
> 
> ```ts
> import { globalStyle } from "./global-style"
> 
> export default { globalStyle }
> ```
> 
> to
> 
> ```ts
> import { globalStyle } from "./global-style"
> 
> export const tokens = { globalStyle }
> ```
> 
> ### 3. `./theme/components/index.ts`
> 
> from:
> 
> ```ts
> import { Container } from "./container"
> 
> export default { Container }
> ```
> 
> to:
> 
> ```ts
> import { Container } from "./container"
> 
> export const components = { Container }
> ```

@odendayoko 
Are there anything wrong? I think the  example you showed at first comment is wrong because `token` is imported with `named-import`.But other example is not. I can understand why we should use `named-export`. Please tell me !!

```index.tsx
import { createRoot } from "react-dom/client"
import { App } from "./app"
import { UIProvider } from "@yamada-ui/react"
import { theme } from "theme"

const container = document.getElementById("app")

const root = createRoot(container!)

root.render(
  <UIProvider theme={theme}>
    <App />
  </UIProvider>,
)
```

**Comment by odendayoko** [comment]
@Shunii85 @hirotomoyamada 
Sorry, I was wrong.`./theme/index.ts` also needs to be modified.
I would like to see a modification to named imports to match the [Yamada UI](https://github.com/yamada-ui/yamada-ui/blob/main/packages/theme/src/index.ts) implementation.

## 2. [Changing Styles](https://yamada-ui.com/styled-system/theming/customize-theme#changing-styles)
from
```ts
// ./theme/styles/index.ts

import { globalStyle } from "./global-style"

export default { globalStyle }

// ./theme/index.ts

import { extendTheme, UsageTheme } from "@yamada-ui/react"
import styles from "./styles"
// import components from './components'
import tokens from "./tokens"
import { semantics } from "./semantics"

```
to
```ts
// ./theme/styles/index.ts

import { globalStyle } from "./global-style"

export const styles = { globalStyle }

// ./theme/index.ts

import { extendTheme, UsageTheme } from "@yamada-ui/react"
import { styles }  from "./styles"
// import components from './components'
import { tokens } from "./tokens"
import { semantics } from "./semantics"

```

## 3. [Changing the Style of Components](https://yamada-ui.com/styled-system/theming/customize-theme#changing-styles)
from
```ts
// ./theme/components/index.ts

import { Container } from "./container"

export default { Container }

// ./theme/index.ts

import { extendTheme, UsageTheme } from "@yamada-ui/react"
import styles from "./styles"
import components from "./components"
import tokens from "./tokens"
import { semantics } from "./semantics"
```
to
```ts
// ./theme/components/index.ts
import { Container } from "./container"

export const components = { Container }

// ./theme/index.ts

import { extendTheme, UsageTheme } from "@yamada-ui/react"
import { styles } from "./styles"
import { components } from './components'
import { tokens } from "./tokens"
import { semantics } from "./semantics"
```

**Comment by Shunii85** [comment]
@odendayoko Thank you! I would.
