### ISSUE TITLE
Add `PasswordInput` component

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#3217]
### Description

Used to collect passwords.

- https://www.chakra-ui.com/docs/components/password-input

### Problem Statement/Justification

It is used frequently in applications and should be provided by default in the Yamada UI.

### Proposed Solution or API

```tsx
<PasswordInput />
```

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

Yes

**Comment by quangnmwork** [comment]
Sir , Can I take on this task .

**Comment by hirotomoyamada** [comment]
@quangnmwork 

Hi, thanks for the comment!

Yes, pls!

You can refer to this source code!Use `@yamada-ui/lucide` icons for `"Show"` and `"Hide"`.

https://yamada-ui.github.io/yamada-ui/?path=/story/components-forms-input--use-element

**Comment by hirotomoyamada** [comment]
@quangnmwork

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.

**Comment by quangnmwork** [comment]
@hirotomoyamada 

Hi , I still working on it . Could you resigin for me.

**Comment by hirotomoyamada** [comment]
@quangnmwork 

OK!

**Comment by hirotomoyamada** [comment]
Fixed #3437
