### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/transitions`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#3229]
package: @yamada-ui/transitions

### Description
`@yamada-ui/transitions` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/transitions/src/flip.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/transitions/src/flip.tsx)
  - [L156](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/transitions/src/flip.tsx#L156)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by nathanlao** [comment]
Hello @hirotomoyamada, can I work on this next?

**Comment by hirotomoyamada** [comment]
Hi, thanks for the comment!

Yes, pls!
