### ISSUE TITLE
Rename `left` and `right` in the name or value of `props` to `start` and `end`

### ISSUE THREAD

**Issue by nathanlao** [yamada-ui/yamada-ui#3283]
### Description

- If left or right is used in the name or value of props, change it to start or end.
	- props to be changed are marked `@deprecated` in v1.

### Problem Statement/Justification

v2.0 enhancement

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

Yes

**Comment by kaehehehe** [comment]
Please remove the triage tag when you start working! :) @nathanlao
