### ISSUE TITLE
Rename `Divider` to `Separator`

### ISSUE THREAD

**Issue by nathanlao** [yamada-ui/yamada-ui#3292]
### Description

package: @yamada-ui/layouts

Enhancement of `<Divider />`

### Problem Statement/Justification

Renaming the component  `<Divider />`  to `<Separator />`
- Add `@deprecated` in v1

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

Create a working branch from v2.0 please

**Comment by MrRobot-fm** [comment]
@nathanlao 
Can i take this task, please?

**Comment by nathanlao** [comment]
Hi @MrRobot-fm, thank you for the comment.

Sorry I believe someone has submitted the PR and it's currently in reviewing 😓

**Comment by MrRobot-fm** [comment]
@nathanlao No problem 😁

**Comment by hirotomoyamada** [comment]
Fixed #3659, #3660
