### ISSUE TITLE
Rename `props`: `is*` eliminates all `is` prefix in the `Modal` component

### ISSUE THREAD

**Issue by nathanlao** [yamada-ui/yamada-ui#3302]
package: @yamada-ui/modal

### Description

Change and unify the names of props. 
- Removing all `is` prefix from `is*`

### Problem Statement/Justification

- For example, `isOpen` becomes `open` and `isDisabled` becomes `disabled`
- Unify `orientation` and `direction` to either one
- props to be changed are marked `@deprecated` in v1

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by MrRobot-fm** [comment]
Hi @nathanlao , can i take this task?

**Comment by nathanlao** [comment]
Hi @MrRobot-fm, thank you for the comment.

I have assigned you and please create a working branch from v2.0.

Good luck!

**Comment by MrRobot-fm** [comment]
@nathanlao 
I have to change only the props with the prefix `is` that was marked `@deprecated`?

**Comment by nathanlao** [comment]
@MrRobot-fm Yes and I believe it includes the docs and demos as well if there are any.
