### ISSUE TITLE
Remove `size` from  `Loading` component

### ISSUE THREAD

**Issue by Haru-0001** [yamada-ui/yamada-ui#3340]
### Description

`@yamada-ui/loading`
Remove `size` from `Loading` component.

### Problem Statement/Justification

Covered by the size of `@yamada-ui/theme`.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by Haru-0001** [comment]
This issue is closed due to the existence of similar issue #3499.

**Comment by nathanlao** [comment]
This issue is closed due to the existence of similar issue https://github.com/yamada-ui/yamada-ui/issues/3499.
