### ISSUE TITLE
Hydration error in Next.js 15

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#3363]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.6.1

### Description

When using `ThemeSchemeScript` or `ColorModeScript`, due to script rewrite `html` and `body` tag, hydration error occurs.
![image](https://github.com/user-attachments/assets/72a1f15f-0e02-42c3-a682-5e1b35d2b233)

Warning will be ignored to add `suppressHydrationWarning` in tag.
https://nextjs.org/docs/messages/react-hydration-error
```tsx
    <html lang="ja" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>

      <body suppressHydrationWarning>
        <YamadaUIScripts />

        <UIProvider config={config} theme={theme}>
          {children}
        </UIProvider>
      </body>
    </html>
```

### Link to Reproduction

https://github.com/108yen/yamada-ui-custom/tree/3407d7147b5c11c96a045dfd0cb234e76c1374a9

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by 108yen** [comment]
https://github.com/mantinedev/mantine/issues/7008

**Comment by hirotomoyamada** [comment]
For now, add `suppressHydrationWarning` to the `html` tag.
