### ISSUE TITLE
Separation of UI and Logic in the `RangeSlider` Component

### ISSUE THREAD

**Issue by kaehehehe** [yamada-ui/yamada-ui#3369]
### Description

Improving code maintainability and readability.

### Proposed Solution or API

Move the `useRangeSlider` code from `range-slider.tsx` to a new file called `use-range-slider.ts`.

### Additional Information

Please create a new branch from 2.0 branch for development.

**Comment by 108yen** [comment]
This issue is duplicated in #3288.
