### ISSUE TITLE
Changed import of `@yamada-ui/lucide` in `forms` of Storybook to `*Icon`.

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#3388]
### Description

Correct the writing style deprecated with this PR.
#3358

For example, fix the parts in `stories/components/data-display/calendar.stories.tsx` that are not imported in `*Icon` format.

```diff
- import { Ghost } from "@yamada-ui/lucide"
+ import { GhostIcon } from "@yamada-ui/lucide"
```

### Problem Statement/Justification

Because it's deprecated.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by Ponraaj** [comment]
Can I work on this?

**Comment by illionillion** [comment]
> Can I work on this?

Yes Please! @Ponraaj

**Comment by Ponraaj** [comment]
@illionillion  I have raised PR for this issue. Kindly check it out
