### ISSUE TITLE
Changed import of `@yamada-ui/lucide` in `navigation` of Storybook to `*Icon`.

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#3400]
### Description

Correct the writing style deprecated with this PR.
#3358

For example, fix the parts in `stories/components/data-display/calendar.stories.tsx` that are not imported in `*Icon` format.

```diff
- import { Ghost } from "@yamada-ui/lucide"
+ import { GhostIcon } from "@yamada-ui/lucide"
```

### Problem Statement/Justification

Because it's deprecated.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by slusy** [comment]
Hey, I would like to work on this

**Comment by illionillion** [comment]
@slusy 
Yes Please!
