### ISSUE TITLE
Changed import of `@yamada-ui/lucide` in `examples` to `*Icon`.

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#3411]
### Description

Modify import of `@yamada-ui/lucide` in `examples/*/src/components/layouts/header.tsx`.

### Problem Statement/Justification

Correct the writing style deprecated with this PR.
#3358

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by sarthakvijayvargiya** [comment]
@illionillion Can i work on this

**Comment by illionillion** [comment]
@sarthakvijayvargiya Yes, please!

**Comment by hirotomoyamada** [comment]
@sarthakvijayvargiya

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.
If you are working on this issue and would like to be reassigned, please contact us.
