### ISSUE TITLE
Changed import of `@yamada-ui/lucide` in `Alert` to `*Icon`.

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#3412]
### Description

Modify import of `@yamada-ui/lucide` in `packages/components/alert`.
Fix the test code as well.

### Problem Statement/Justification

Correct the writing style deprecated with this PR.
#3358

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by eraser5th** [comment]
I will try it.

**Comment by illionillion** [comment]
@eraser5th 
Yes please!
