### ISSUE TITLE
Rename `direction` to `orientation`

### ISSUE THREAD

**Issue by koralle** [yamada-ui/yamada-ui#3428]
### Description

There is a mix of `direction` and `orientation` as the name of the property that specifies the layout orientation.  
In v2.0, this will be unified to `orientation`.

## ToDo

- [ ] Rename `direction` to `orientation`
- [ ] add `@deprecated` to `direction`

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by sarthakvijayvargiya** [comment]
hi @koralle Can i work on this

**Comment by koralle** [comment]
@sarthakvijayvargiya 

That's fine.
You need to work on this issue following these steps:

1. Create a working branch from the `main` branch.
2. Create a new `orientation` prop that serves the same purpose as the `direction` prop where the `direction` prop is currently being used.
3. Add `@deprecated` JSDoc to the `direction` prop where you created the new `orientation` prop in step 2.
4. Create a Pull Request against the `main` branch containing the work from steps 2 and 3.
5. After the Pull Request from step 4 is merged, create a new working branch from the `v2.0` branch.
6. Remove the `direction` prop that has been marked with `@deprecated`.
7. Create a Pull Request containing the work from step 6.

**Comment by hirotomoyamada** [comment]
@koralle @sarthakvijayvargiya 

Hi, Please create a PR for each package as it makes the review process more difficult. If necessary, I would like to see issues created for them as well.

**Comment by kaehehehe** [comment]
@hirotomoyamada  @koralle @sarthakvijayvargiya 

It is difficult to determine which components have been completed and which have not, so I created issues for each package.
