### ISSUE TITLE
The size of `@yamada-ui/react` package is very large

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3474]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.6.3

### Description

The package size seem to have increased by more than 2x since 1.6.0.

![Package size image](https://media.discordapp.net/attachments/1114670052340416514/1306534053507502132/image.png?ex=67370428&is=6735b2a8&hm=b0b10f00f58adbed1c4e35901c926c15f20b48fc212aabf8a56e5e3139678b21&=&format=webp&quality=lossless&width=1043&height=702)

### Link to Reproduction

https://bundlephobia.com/package/@yamada-ui/react@1.6.3

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@taroj1205 

This is bloated by the inclusion of `@yamada-ui/lucide` in `@yamada-ui/react`.

However, now that tree-shaking has become the norm, bundle size does not seem to be that important to be aware of.
