### ISSUE TITLE
Repeatedly prompts brakpoints with undefined warnings

### ISSUE THREAD

**Issue by cangSDARM** [yamada-ui/yamada-ui#3506]
### Which package has an issue?

@yamada-ui/modal

### Package Version

1.4.4

### Description

When using a Modal package alone, it repeatedly prompts brakpoints with undefined warnings

![image](https://github.com/user-attachments/assets/d450bd44-68ac-492e-b3a1-f63e433f4573)

### Steps to Reproduce

1. install @yamada-ui/modal individually
2. use Modal
3. See error

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by taroj1205** [comment]
I was able to reproduce this too!
```
useBreakpoint: `breakpoints` is undefined. Seems you forgot to put theme in `breakpoints`
```
with the code below
```tsx
"use client";
import { Button, useDisclosure } from "@yamada-ui/react";
import { Modal, ModalBody, ModalFooter, ModalHeader } from "@yamada-ui/modal";

export const ModalComponent = () => {
    const { isOpen, onOpen, onClose } = useDisclosure();
    return (
        <>
            <Button onClick={onOpen}>Open Modal</Button>
            <Modal isOpen={isOpen} onClose={onClose}>
                <ModalHeader>ドラゴンボール</ModalHeader>

                <ModalBody>
                    『ドラゴンボール』（DRAGON
                    BALL）は、鳥山明による日本の漫画作品。『週刊少年ジャンプ』（集英社）にて1984年51号から1995年25号まで連載された。世界中に散らばった七つの球をすべて集めると、どんな願いも一つだけ叶えられるという秘宝・ドラゴンボールと、主人公・孫悟空（そん・ごくう）を中心に展開する、「冒険」「夢」「バトル」「友情」などを描いた長編漫画。
                </ModalBody>

                <ModalFooter>
                    <Button variant="ghost" onClick={onClose}>
                        とじる
                    </Button>
                    <Button colorScheme="primary">Wikipedia</Button>
                </ModalFooter>
            </Modal>
        </>
    );
};
```

**Comment by hirotomoyamada** [comment]
@cangSDARM @taroj1205 

Hi, some components require the use of `ThemeProvider`.

https://yamada-ui.com/getting-started/installation/minimal#if-you-want-to-use-tokens-such-as-colors-and-spaces

ResetStyle` and `GlobalStyle` are not required.

If you do not use `baseTheme`, defining only `breakpoints` in `theme` will work fine.

**Comment by cangSDARM** [comment]
@hirotomoyamada If that's the case, I think a hint is needed in the readme. This is a great help to people who have similar problems later on

**Comment by hirotomoyamada** [comment]
@cangSDARM 

Thanks for the feedback! Yamada UI is currently developing v2.0. We would like to improve it by incorporating the feedback!
