### ISSUE TITLE
Rename props: `direction` to `orientation` in `Card` package

### ISSUE THREAD

**Issue by kaehehehe** [yamada-ui/yamada-ui#3508]
### Description

related #3428

### Problem Statement/Justification

- [ ] Rename `direction` to `orientation`
- [ ] Add `@deprecated` to `direction`

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by hirotomoyamada** [comment]
@kaehehehe 

This does not need to be worked on. This `direction` is a short hand for `flexDirection`.
