### ISSUE TITLE
Rename `direction` to `orientation` in `yamada-ui/card`

### ISSUE THREAD

**Issue by cidkumagai** [yamada-ui/yamada-ui#3515]
related #3428

### Description

There is a mix of direction and orientation as the name of the property that specifies the layout orientation.
In `v2.0`, this will be unified to orientation.

### ToDo
- [ ] Rename direction to orientation
- [ ] add @deprecated to direction

**Comment by mei28** [comment]
is this the same as #3508?

**Comment by kaehehehe** [comment]
It seems that the issue is duplicated, so I will close it.
