### ISSUE TITLE
Rename `direction` to `orientation` in `@yamada-ui/resizable`

### ISSUE THREAD

**Issue by cidkumagai** [yamada-ui/yamada-ui#3516]
related #3428

### Description

There is a mix of direction and orientation as the name of the property that specifies the layout orientation.
In v2.0, this will be unified to orientation.

### ToDo

- [ ] Rename `direction` to `orientation`
- [ ] add `@deprecated` to `direction`

### Problem Statement/Justification

No Response

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by myheadisempty** [comment]
Yo, @cidkumagai, can i help with this issue?

**Comment by cidkumagai** [comment]
@myheadisempty 
I'm sorry, someone is already working on it.
