### ISSUE TITLE
Rename `direction` to `orientation` in `@yamada-ui/toggle`

### ISSUE THREAD

**Issue by cidkumagai** [yamada-ui/yamada-ui#3517]
related #3428

### Description

There is a mix of direction and orientation as the name of the property that specifies the layout orientation.
In v2.0, this will be unified to orientation.

### ToDo

- [ ] Rename `direction` to `orientation`
- [ ] add `@deprecated` to `direction`

### Problem Statement/Justification

No response

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by kaehehehe** [comment]
It seems that the issue is duplicated, so I will close it.
