### ISSUE TITLE
Rename `props`: `is*` eliminates all `is` prefix in the`Input` package

### ISSUE THREAD

**Issue by nathanlao** [yamada-ui/yamada-ui#3524]
### Description

Change and unify the names of props.
Removing all is prefix from is*

### Problem Statement/Justification

For example, isOpen becomes open and isDisabled becomes disabled.

### Proposed Solution or API

props to be changed are marked `@deprecated` in v1

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by kaehehehe** [comment]
The code shows that the issue is already resolved.

**Comment by nathanlao** [comment]
Hi @kaehehehe, thank you for pointing it out, just a quick follow up: I see that in this [input-element.tsx](https://github.com/yamada-ui/yamada-ui/blob/main/packages/components/input/src/input-element.tsx), the `isClick` prop is deprecated, and replaced wiht `isClickable`. Should we consider removing the is prefix for this prop, even though this component appears to be for internal use?

**Comment by kaehehehe** [comment]
HI @nathanlao. Thanks for the comment! Something feels off after looking at it again. I think we should deprecate the `isClickable` prop.

**Comment by kaehehehe** [comment]
Hi @hirotomoyamada, I have a question!
In the Interface `InputElementOptions`, the `isClick` prop is deprecated, and it suggests using the `isClickable` prop instead. Should we also add deprecated to the `isClickable` prop to indicate that it should be replaced with the `clickable` prop? It feels a bit off, but I want to confirm if that's necessary.

![スクリーンショット 2024-11-20 111001](https://github.com/user-attachments/assets/de1ded7b-33f7-4f82-a930-89f5c540445f)
