### ISSUE TITLE
Replace `ResizableTriggerIcon` with `LucideIcon`

### ISSUE THREAD

**Issue by kaehehehe** [yamada-ui/yamada-ui#3536]
### Description

Replace `ResizableTriggerIcon` with `LucideIcon`

### Problem Statement/Justification

Replace the icons from `@yamada-ui/icon` with those from `@yamada-ui/lucide`.

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by Rakesh-SP330** [comment]
can i work on this?
