### ISSUE TITLE
Loss of Visual Focus Feedback on Disabled but Focusable Elements in `AutocompleteOption` 

### ISSUE THREAD

**Issue by odendayoko** [yamada-ui/yamada-ui#3571]
### Which package has an issue?

@yamada-ui/autocomplete

### Package Version

1.6.5

### Description

After clicking on an element that is `disabled` and `focusable`, the visual feedback when focusing on this element is lost.

Elements with `focusable` should change background color when focused, even if `disabled`, to visually convey that the element is focused.
However, if you click on a `disabled` element and then move the focus to this element, no background color change occurs, making it difficult to visually determine if the element is focused.

```ts
export const isOptionFocusable: Story = () => {
  return (
    <Autocomplete placeholder="キャラクターを選択">
      <AutocompleteOption value="孫悟空">孫悟空</AutocompleteOption>
      <AutocompleteOption disabled focusable value="ベジータ">
        ベジータ
      </AutocompleteOption>
      <AutocompleteOption value="フリーザ">フリーザ</AutocompleteOption>
    </Autocomplete>
  )
}
```

https://github.com/user-attachments/assets/33dc3074-8890-48ae-9109-ccf1e9e01052

### Steps to Reproduce

1. Click on `Autocomplete` to display popover
2. Use the up and down arrow keys to move the focus (Background color changes normally at this point)
3. Click on an element with `disabled`
4. Use the up and down arrow keys to move the focus
5. See error

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information
This bug has been identified in one example of Storybook.
https://yamada-ui.github.io/yamada-ui/?path=/story/components-forms-autocomplete--is-option-focusable

**Comment by hirotomoyamada** [comment]
@odendayoko 

Hi, the `focusable` is `props` for keyboard operation, not for mouse operation.

What do you expect when using a mouse?

**Comment by odendayoko** [comment]
@hirotomoyamada 
Thank you for your question. You’re right that the `focusable` is primarily intended for keyboard operation. 

However even after clicking a `disabled` element with a mouse, I believe the element should remain `focusable` and visually indicate focus , such as by changing the background color when focused.
