### ISSUE TITLE
Rename `props`: `is*` eliminates all `is` prefix in the `color-picker` package

### ISSUE THREAD

**Issue by nathanlao** [yamada-ui/yamada-ui#3572]
### Description

Change and unify the names of props.
Removing all is prefix from is*

### Problem Statement/Justification

For example, `isOpen` becomes `open` and `isDisabled` becomes `disabled`.

### Proposed Solution or API

props to be changed are marked `@deprecated` in v1

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by kaehehehe** [comment]
Hi, @hirotomoyamada. The prop `rounded` is already in use, so we cannot change `isRounded` to `rounded`. What would be a good alternative name?

```tsx
interface ColorSwatchOptions {
  /**
   * The color used for the swatch element.
   *
   * @default "#ffffff00"
   */
  color?: CSSUIProps["color"]
  /**
   * If `true`, the color swatch will be perfectly round. Else, it'll be slightly round.
   *
   * @default false
   */
  isRounded?: boolean
  /**
   * The overlay used for the swatch element.
   */
  overlays?: HTMLUIProps[]
  /**
   * If `true`, the swatch element has an inner `box-shadow`.
   *
   * @default true
   */
  withShadow?: boolean
}
```

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, I was just thinking about this myself while working on another project. How about `fullRounded`?There are other components with `fullHeight`, so I thought it would be better to match.
