### ISSUE TITLE
Rename `props`: `is*` eliminates all `is` prefix in the `checkbox` package

### ISSUE THREAD

**Issue by nathanlao** [yamada-ui/yamada-ui#3574]
### Description

Change and unify the names of props.
Removing all is prefix from is*

### Problem Statement/Justification

For example, `isOpen` becomes `open` and `isDisabled` becomes `disabled`.

### Proposed Solution or API

props to be changed are marked `@deprecated` in v1

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by kaehehehe** [comment]
I recall that some time ago, it was mentioned that `isNative` would be deprecated. Is my memory correct, or would it be better to drop the is prefix and simply add a `native` prop instead? @hirotomoyamada 

```tsx
export interface UseCheckboxGroupProps<Y extends number | string = string> {
  /**
   * The initial value of the checkbox group.
   */
  defaultValue?: Y[]
  /**
   * If `true`, input elements will receive `checked` attribute instead of `isChecked`.
   *
   * This assumes, you're using native radio inputs.
   *
   * @default false
   */
  isNative?: boolean
  /**
   * The value of the checkbox group.
   */
  value?: Y[]
  /**
   * The callback fired when any children checkbox is checked or unchecked.
   */
  onChange?: (value: Y[]) => void
}
```

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, correct. Add `@deprecated` to `isNative`. You do not need to add `native`.
