### ISSUE TITLE
Rename `props`: `is*` eliminates all `is` prefix in the `ripple` package

### ISSUE THREAD

**Issue by kaehehehe** [yamada-ui/yamada-ui#3584]
### Description

Change and unify the names of props.
Removing all is prefix from is*

### Problem Statement/Justification

For example, `isOpen` becomes `open` and `isDisabled` becomes `disabled`.

### Alternatives

props to be changed are marked `@deprecated` in v1

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

Yes

**Comment by kaehehehe** [comment]
Hi, @hirotomoyamada. In a situation where both `disabled` and `isDisabled` props already exist, what should we do?

```tsx
export interface UseRippleProps<T = HTMLElement> {
  disabled?: boolean
  isDisabled?: boolean
  onPointerDown?: PointerEventHandler<T>
}
```

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, Only `isDisabled` should be deprecated.
