### ISSUE TITLE
Rename `props`: `is*` eliminates all `is` prefix in the `progress` package

### ISSUE THREAD

**Issue by kaehehehe** [yamada-ui/yamada-ui#3621]
### Description

Change and unify the names of props.
Removing all is prefix from is*

### Problem Statement/Justification

For example, `isOpen` becomes `open` and `isDisabled` becomes `disabled`.

### Alternatives

props to be changed are marked `@deprecated` in v1

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by kaehehehe** [comment]
@hirotomoyamada Hi, the `isAnimation` of the `ProgressOptions` interface, what do you think it should be changed to? `fullAnimation` seems a bit strange to me...

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, I'm having trouble naming it.Also, I feel that `isAnimation` is not in demand and could be removed. If developers want to add animation, they can set it.
