### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/checkbox`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#3650]
package: @yamada-ui/checkbox

### Description
`@yamada-ui/checkbox` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/checkbox/src/checkbox-card-addon.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/checkbox-card-addon.tsx)
  - [L11](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/checkbox-card-addon.tsx#L11)
- [packages/components/checkbox/src/checkbox-card.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/checkbox-card.tsx)
  - [L120](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/checkbox-card.tsx#L120)
  - [L124](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/checkbox-card.tsx#L124)
  - [L168](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/checkbox-card.tsx#L168)
  - [L210](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/checkbox-card.tsx#L210)
- [packages/components/checkbox/src/use-checkbox.ts](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts)
  - [L158](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts#L158)
  - [L201](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts#L201)
  - [L207](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts#L207)
  - [L230](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts#L230)
  - [L251](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts#L251)
  - [L328](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts#L328)
  - [L332](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/checkbox/src/use-checkbox.ts#L332)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by gauravnadkarni** [comment]
Hi @hirotomoyamada, Can you please assign this to me if nobody is working on it?

**Comment by hirotomoyamada** [comment]
@gauravnadkarni 

Hi, thanks for the comment!

Yes, pls!

**Comment by gauravnadkarni** [comment]
This is ready for review. @hirotomoyamada
