### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/empty-state`

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#3652]
package: @yamada-ui/empty-state

### Description
`@yamada-ui/empty-state` has a test coverage of less than 95%. We will enhance it to above 95%.

### Target files
- [packages/components/empty-state/src/empty-state.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/empty-state/src/empty-state.tsx)
  - [L91](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/empty-state/src/empty-state.tsx#L91)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

**Comment by hirotomoyamada** [comment]
@gauravnadkarni 

Hi, thanks for the comment!

Yes, pls!

**Comment by gauravnadkarni** [comment]
@hirotomoyamada Thank you for assigning this to me. This is ready for review.
