### ISSUE TITLE
There is an img tag that is not shown in the document.

### ISSUE THREAD

**Issue by kurakke** [yamada-ui/yamada-ui#3658]
### Provide the exact quote of the error or issue

There is an img tag that is not displayed in the Bronze Sponsor section of the document.

If you visit `https://yamada-ui.com/community/team` and check the bronze sponsor in the developer tools, you can see the hidden img tag.

<img width="853" alt="image" src="https://github.com/user-attachments/assets/f8b5b216-d152-49d3-80d6-e9946b7a22a4">

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/community/team

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@kurakke 

This isssue is not a problem.
