### ISSUE TITLE
`FormatNumber` and `FormatByte` does not appear properly in search

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3687]
### Provide the exact quote of the error or issue

The `FormatNumber`, `FormatByte` and `useFormatByte` component does not appear properly in the search.

<details><summary><code>FormatNumber</code></summary>
<img src="https://github.com/user-attachments/assets/7cc75df3-558e-4b06-8aa9-ed9b875efe26" />
</details> 

<details><summary><code>FormatByte</code></summary>
<img src="https://github.com/user-attachments/assets/bd88225f-125d-44f7-b34c-bba3a1ef550f" />
</details> 

<details><summary><code>useFormatByte</code></summary>
<img src="https://github.com/user-attachments/assets/0dda79d9-c4a9-45bf-aec0-414968840368" />
</details> 

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@taroj1205 

It has already been corrected.
