### ISSUE TITLE
Use `<For />` in `Float` documentation

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3697]
### Provide the exact quote of the error or issue
We should use `<For />` component when repeating a component
e.g.
```tsx
<For each={items}>{(item, index) => <Text key={index} fontWeight="bold">{item}</Text>}</For>
```

https://yamada-ui.com/components/layouts/float

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by shunji-muto** [comment]
初めまして。
こちらのissueのお手伝いをしたいのですが、OSSへの貢献を今までしたことがなく、勝手がわかりません。

どのようにコードの変更をお伝えして、Pull Requestを送れば良いでしょうか？
（branchを作る権限がないため、どのように変更をお伝えすれば良いかわかりません）

お手数おかけしますが、ご教授いただけないでしょうか？
