### ISSUE TITLE
Use `<For />` in `SegmentedControl` documentation

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3741]
### Provide the exact quote of the error or issue
We should use `<For />` component when repeating a component
e.g.
```tsx
<For each={items}>{(item, index) => <Text key={index} fontWeight="bold">{item}</Text>}</For>
```

https://yamada-ui.com/components/forms/segmented-control

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by kaehehehe** [comment]
@hirotomoyamada 
The `SegmentedControl` cannot use the `For` component, right? If that's the case, I will close this issue.

![Image](https://github.com/user-attachments/assets/de08570a-6fc1-498e-b19f-618d5a02bf98)

**Comment by hirotomoyamada** [comment]
@kaehehehe 

Hi, This, like `Stack`, gets the number of child elements, so `For` cannot be used.
