### ISSUE TITLE
Use `<For />` in `Progress` documentation

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3776]
### Provide the exact quote of the error or issue
We should use `<For />` component when repeating a component
e.g.
```tsx
<For each={items}>{(item, index) => <Text key={index} fontWeight="bold">{item}</Text>}</For>
```

https://yamada-ui.com/components/feedback/progress

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by HT0323** [comment]
I would like to work on this issue.

**Comment by kaehehehe** [comment]
> I would like to work on this issue.

Thank you! I will assign you.
