### ISSUE TITLE
Use `<For />` in `Avatar` documentation

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3779]
### Provide the exact quote of the error or issue
We should use `<For />` component when repeating a component
e.g.
```tsx
<For each={items}>{(item, index) => <Text key={index} fontWeight="bold">{item}</Text>}</For>
```

https://yamada-ui.com/components/media and icons/avatar

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by reibomaru** [comment]
Can I have this issue assigned to me?

**Comment by kaehehehe** [comment]
@reibomaru 
Of course! I'll make sure this issue is assigned to you.
