### ISSUE TITLE
`ScaleFade` does nothing when toggle

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3791]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.7.0

### Description

When I click on the toggle button in the [documentation](https://yamada-ui.com/components/transitions/scale-fade#usage), it seems to not do anything.

https://github.com/user-attachments/assets/c9730d7b-5323-4b06-99d1-dde6970c7a0d

### Link to Reproduction

https://yamada-ui.com/components/transitions/scale-fade#usage

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@taroj1205 @nathanlao 

Hi, This #3420 seems to be the cause.
