### ISSUE TITLE
Control externally section in `Slider` documentation should use `ButtonGroup`

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3792]
### Provide the exact quote of the error or issue

The slider's control externally section example should use `<ButtonGroup />` component.
https://yamada-ui.com/components/forms/slider#control-externally-only

Below is an example of how we could fix it.

```tsx
const [value, setValue] = useState<number>(50)

return (
  <>
    <Text>Value: {value}</Text>

    <Slider value={value} step={10} focusThumbOnChange={false} />

    <ButtonGroup as={Center} w="full" gap="md">
      <Button
        isDisabled={value === 0}
        onClick={() => setValue((prev) => (prev !== 0 ? prev - 10 : prev))}
      >
        -10
      </Button>
      <Button
        isDisabled={value === 100}
        colorScheme="blue"
        onClick={() => setValue((prev) => (prev !== 100 ? prev + 10 : prev))}
      >
        +10
      </Button>
    </ButtonGroup>
  </>
)
```

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by 2NNS-V** [comment]
Can I work on this section? kindly assign it to me!

**Comment by hirotomoyamada** [comment]
@2NNS-V 

Hi, thanks for the comment!

Yes, pls!
