### ISSUE TITLE
The `For` component is appearing 3 times in search

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3794]
### Provide the exact quote of the error or issue

When I search "For" in search, `For` component appears 3 times.

![image](https://github.com/user-attachments/assets/12a9fc11-8250-407d-acac-7a772048bb94)

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@taroj1205 

It has already been corrected.
