### ISSUE TITLE
Popover location for `DonutChart` is covering the entire chart

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3795]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.7.0

### Description

When hovering over `DonutChart`, the popover goes over the donut chart, covering the entire chart.

![image](https://github.com/user-attachments/assets/4468c20c-90fe-46b1-929d-ee23aaf4c941)

### Link to Reproduction

https://yamada-ui.com/components/data-display/donut-chart

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
@108yen 

Hi, was this possible to fix?

**Comment by hirotomoyamada** [comment]
@taroj1205 @108yen 

This is acceptable because the developer can change the size of the chart in response to the size of the tooltip.
