### ISSUE TITLE
Close the `Drawer` by dragging

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#548]
### Description

Currently, the `Drawer` closes by clicking outside or by clicking the `CloseButton`. We felt it would be good to place a draggable element on the edge of the `Drawer`, like the `iOS Drawer`, and have a process to close it when it is dragged for a certain amount of time.

### Problem Statement/Justification

On mobile, users want to be able to close the `Drawer` by dragging it from a usability perspective.

### Proposed Solution or API

Added `closeOnDrag` props.

```tsx
<Drawer isOpen={isOpen} onClose={onClose} closeOnDrag>
  {/* contents */}
</Drawer>
```

**Comment by kotaesaki** [comment]
Can I work on this Issue? Thanks!

**Comment by hirotomoyamada** [comment]
@kotaesaki 

Hi, thanks for the comment!

Yes, please! Assign it to you. Good luck!

**Comment by hirotomoyamada** [comment]
@kotaesaki 

こんにちは！

このイシューの状況は、どうですか？

明日、このイシューのアサインを初期の状態に戻します。

このイシューを取り組んでおり、延長する場合は、こちらに連絡をください。

**Comment by hirotomoyamada** [comment]
@kotaesaki 

Hi, Thanks for the working on this issue!

What is the status of this issue?

Tomorrow, We will return this issue assignment to initial state.

If you are working on this issue and would like to extend it, please contact us.

**Comment by hirotomoyamada** [comment]
@kotaesaki

Hi, Thanks for the working on this issue!

We will return this issue assignment to initial state.

If you are working on this issue and would like to be reassigned, please contact us.

**Comment by yasunogithub** [comment]
@hirotomoyamada 
Can I work on this issue?
Here  is my PR.
#604 
please check it. thanks.

**Comment by taroj1205** [comment]
@yasunogithub 
Hi, thanks for the comment!
I'll assign to it to you.
