### ISSUE TITLE
ScrollArea does not hide scroll-bar on Safari with type prop "hover" and "scroll"

### ISSUE THREAD

**Issue by illionillion** [yamada-ui/yamada-ui#757]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.5

### Description

The same bug as this issue occurs in safari.

#745

https://github.com/hirotomoyamada/yamada-ui/assets/60034520/75d8aef9-7141-41c6-91ef-4f4aba22edf5

### Link to Reproduction

https://hirotomoyamada.github.io/yamada-ui/?path=/story/components-data-display-scrollarea--with-type

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

Safari

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by AVAM16** [comment]
Can I take the issue?
It is happening in both Firefox and Safari in MacOS.

**Comment by AVAM16** [comment]
take

**Comment by AVAM16** [comment]
take

**Comment by hirotomoyamada** [comment]
@AVAM16 

Hi, ok!

I'll assign this issue to you.
