### ISSUE TITLE
Enhance Test Coverage for Components

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#775]
### Description

Enhance test coverage for components with less than 80% coverage to meet or exceed 80%.

### Problem Statement/Justification

Increasing test coverage to 80% or above is crucial for quality and stability.

### Proposed Solution or API

Prioritise components below 80% for test coverage enhancement.

### Alternatives

No response

#### How to confirm test coverage on local
1. execute `pnpm test:coverage` on your terminal
2. access to `http://localhost:4173/` on your browser

#### How to confirm test coverage on main branch
access to below URL
https://yamada-ui.com/coverage/index.html

**Comment by hirotomoyamada** [comment]
Fixed
