### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/highlight`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#785]
related: #775

### Description
Enhance test coverage for components with less than 80% coverage to meet or exceed 80%.

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

**Comment by txxxxc** [comment]
@setodeve (cc: @hirotomoyamada )
はじめまして！こちら参加させていただきたいです。
ご確認よろしくお願いします！

**Comment by hirotomoyamada** [comment]
@txxxxc 

はじめまして！

ぜひ、参加してほしいです。

アサインを割り当てます。幸運を！
