### ISSUE TITLE
Enhance Test Coverage for `@yamada-ui/layouts`

### ISSUE THREAD

**Issue by setodeve** [yamada-ui/yamada-ui#786]
related: #775

### Description
Enhance test coverage for components with less than 80% coverage to meet or exceed 80%.

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

**Comment by txxxxc** [comment]
@setodeve @hirotomoyamada 
Can I contribute this issue?

**Comment by setodeve** [comment]
@txxxxc 
Thank you !
I assigned you. Good luck !
