### ISSUE TITLE
Add documentation about how to test ui component

### ISSUE THREAD

**Issue by Sahillather002** [yamada-ui/yamada-ui#846]
### Description

I was trying to test the ui component but couldn't able to get the idea around it.
Please help me with the same.

### Problem Statement/Justification

![image](https://github.com/hirotomoyamada/yamada-ui/assets/72077931/103d1095-920d-4b12-a542-ea9f89d6d0cb)

**Comment by hirotomoyamada** [comment]
Hi, thanks for the issue.

I agree too.
We would like to discuss this with the test team and create a test document.

**Comment by hirotomoyamada** [comment]
@koralle 

Hi, assign a testing team.

**Comment by Sahillather002** [comment]
Thanks @hirotomoyamada it will be great help to understand and apply some improvements.

**Comment by hirotomoyamada** [comment]
Let's talk in #868 discussion

**Comment by hirotomoyamada** [comment]
@Sahillather002 

Let's talk in #868 discussion

**Comment by hirotomoyamada** [comment]
Fixed #962
