### ISSUE TITLE
The `Notice` component references theme tokens for styling.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#911]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.8

### Description

Yamada UI allows you to use components without applying a theme. It is a mistake to use theme tokens inside components.

```tsx
status={status}
variant={variant}
colorScheme={colorScheme}
alignItems="start"
boxShadow="lg"
className={cx("ui-notice", className)}
pe={isClosable ? 8 : undefined}
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by Taiki0807** [comment]
@hirotomoyamada 
このissueに取り組んでみたいです。
