### ISSUE TITLE
The `Skeleton` component references theme tokens for styling.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#918]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.8

### Description

Yamada UI allows you to use components without applying a theme. It is a mistake to use theme tokens inside components.

```tsx
const css: CSSUIObject = {
  w: isFitContent ? "fit-content" : "100%",
  maxW: "100%",
  h: isFitContent ? "fit-content" : "4",
  boxShadow: "none",
  backgroundClip: "padding-box",
  cursor: "default",
  color: "transparent",
  pointerEvents: "none",
  userSelect: "none",
  "&::before, &::after, *": {
    visibility: "hidden",
  },
  ...styles,
}
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by professorabhay** [comment]
Hey @hirotomoyamada, So we have to remove these style property?

**Comment by hirotomoyamada** [comment]
@professorabhay 

Hi, thanks for the comment!

Rather than removing these style properties, replace them with the theme's token values.
