### ISSUE TITLE
[Fix] Warnings when runnning `pnpm lint`

### ISSUE THREAD

**Issue by koralle** [yamada-ui/yamada-ui#956]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.8

### Description

When I run pnpm lint, the following warning message is displayed.

The message is as follows:

```
❯ pnpm lint

> yamada-ui@1.0.0 lint /Users/path/to/yamada-ui
> eslint packages/**/**/src scripts/**/** vitest.config.mts vite.config.lcov-report.mts --ext .ts,.tsx,.mts --max-warnings 0 --config .eslintrc --cache

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.4.0

YOUR TYPESCRIPT VERSION: 5.4.2

Please only submit bug reports when using the officially supported version.

=============
```

### Steps to Reproduce

1. Run `pnpm lint`

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by hirotomoyamada** [comment]
It was resolved after updating eslint.
