### ISSUE TITLE
The type definition for the property set within `_media` is insufficient.

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#972]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.0

### Description

For example, `aspectRatio` should also accept `minAspectRatio` and `maxAspectRatio`. However, this is not defined.

Add the missing properties using [@media](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_features)  as a reference.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

**Comment by txxxxc** [comment]
Can I contribute this issue?

**Comment by hirotomoyamada** [comment]
Fixed #1005
