### ISSUE TITLE
`IconButton` contains unnecessary code

### ISSUE THREAD

**Issue by hirotomoyamada** [yamada-ui/yamada-ui#980]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.9

### Description

```
  /**
   * If `true`, the button will be perfectly round. Else, it'll be slightly round.
   *
   * @default false
   */
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by suzukisan22** [comment]
can I contribute this??

**Comment by hirotomoyamada** [comment]
@suzukisan22

Hi, thanks for the comment!

Yes, please. Ill assign this issue to you.
